### ISSUE TITLE
Etcher not going through subprocess

### ISSUE THREAD

**Issue by afdaniele** [duckietown/duckietown-shell-commands#1]
Issue with the command `init-sd-card`.

Looks like `etcher` is using some low-level API to talk to the shell that is not going through Python’s subprocess.

**Comment by AndreaCensi** [comment]
solved?

**Comment by afdaniele** [comment]
Nope. It is still not possible to flash the SD card using the shell. Everything printed by `etcher` does not show up in the dt-shell. Running the script in bash works fine.

**Comment by AndreaCensi** [comment]
@afdaniele I flashed 5 cards yesterday. What is your error?

**Comment by AndreaCensi** [comment]
If you have a chance actually try #3 which is a bit more user friendly.

**Comment by AndreaCensi** [comment]
I think this is outdated.
