### ISSUE TITLE
Hangs of dts challenges submit

### ISSUE THREAD

**Issue by bhairavmehta95** [duckietown/duckietown-shell-commands#100]
Running `dts challenges submit`, my Docker container is built and tagged, and the the shell hangs.

`Successfully tagged bhairavmehta95/aido-submissions:2019_04_09_18_20_21` is the last line I see.

**Comment by liampaull** [comment]
@AndreaCensi ?

**Comment by AndreaCensi** [comment]
@bhairavmehta95 @liampaull found the issue.
The "hang" is because the push was happening in the background.

fixed in new shell


p.s. please assign, not mention
