### ISSUE TITLE
dts demo command not working

### ISSUE THREAD

**Issue by gibernas** [duckietown/duckietown-shell-commands#102]
@liampaull 
Running 

     dts duckiebot demo --demo_name joystick --duckiebot_name ![duckiebot_name]

Gets stuck, inside the created container the ouput of the logs is:

![Screenshot from 2019-04-10 15-55-26](https://user-images.githubusercontent.com/22998704/55885368-1d8f2880-5baa-11e9-9993-6f79f036b692.png)

Version of shell and commands is:
INFO:dts:duckietown-shell 4.0.11
Duckietown Shell commands version 4.0.4

**Comment by liampaull** [comment]
I can't truly reproduce but I did fix a few things along the way. 

@gibernas can you retry (pull the appropriate containers first). Also make sure that you have a calibrated robot?

**Comment by liampaull** [comment]
@gibernas I think this can be closed right?

**Comment by gibernas** [comment]
Fixed
