### ISSUE TITLE
[minor] 404 Not found for user that hasn't submitted nothing yet

### ISSUE THREAD

**Issue by AleksandarPetrov** [duckietown/duckietown-shell-commands#108]
I just started following the instructions on the docs. Running `dts challenges info` tells me: 

> You can find the list of your submissions at the page:
>     :  
>     :      https://challenges.duckietown.org/v3/humans/users/844

However, the webpage shows 

> 404 Not Found
> The resource could not be found.
> 
> No user with ID 844 found 

My guess is that this is because I haven't submitted anything yet. Although it would be better to simply show an empty submissions page.

**Comment by AndreaCensi** [comment]
verified it does not happen anymore
