### ISSUE TITLE
start_gui_tools should work for "default" 

### ISSUE THREAD

**Issue by liampaull** [duckietown/duckietown-shell-commands#111]
if there is no real robot but we are running the sim_lanefollowing demo - we should be able to run start_gui_tools and it should be able to use it

**Comment by jasonhu5** [comment]
@liampaull Is this still pending action/relevant?

**Comment by afdaniele** [comment]
Tracked here: https://ethidsc.atlassian.net/browse/DTSW-2434 (private link)
