### ISSUE TITLE
define challlenge expects that the step images are pulled

### ISSUE THREAD

**Issue by AleksandarPetrov** [duckietown/duckietown-shell-commands#115]
@AndreaCensi 

It seems that if we supply `image` instead of `build` to an evaluation step, `dts challenges define` does not pull the image, but expects that it is pulled already. If it is not, it fails with:

`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/images/duckietown/cslam-wes-quackerson/json`

This is a serious issue because even if one has the images pulled, there's no guarantee that it is the latest version.

https://github.com/duckietown/duckietown-shell-commands/blob/e3f9aead76b1018749f6b4acd1c07bb5e3aed3b6/challenges/define/command.py#L114-L122

**Comment by AndreaCensi** [comment]
best practice is to always build a repo - and import from the previous one using "FROM XXX".

**Comment by AndreaCensi** [comment]
Also it is necessary to make sure you are pushing things to repos with right permissions.
