### ISSUE TITLE
No such container: joystick_cli_duckiebot

### ISSUE THREAD

**Issue by na018** [duckietown/duckietown-shell-commands#116]
We followed the manual control tutorial from [rc_control](http://docs.duckietown.org/DT18/opmanual_duckiebot/out/rc_control.html).

We successfully run 
`
docker -H hostname.local run -dit --privileged --name roscore --net host -v /data:/data --restart unless-stopped duckietown/rpi-ros-kinetic-roscore:master18`
and 
`docker -H hostname.local run -dit --privileged --name joystick --network=host -v /data:/data duckietown/rpi-duckiebot-joystick-demo:master18
`.

But when we try to execute ` dts duckiebot keyboard_control hostname` no window for controlling the bot appears. Instead we get the following error:

`
INFO:dts:duckietown-shell-commands 4.0.22
INFO:duckietown-challenges:duckietown-challenges 4.0.30
WARNING:dts:couldn't remove existing container: 404 Client Error: Not Found ("No such container: joystick_cli_duckiebot")
INFO:dts:Running joystick_cli_duckiebot on localhost with environment vars: {'HOSTNAME': 'duckiebot', 'ROS_MASTER': 'duckiebot', 'DUCKIEBOT_NAME': 'duckiebot', 'ROS_MASTER_URI': 'http://172.20.10.6:11311'}

`

at some point 'Enter direction(a,w,s,d)--> ' appears, but the bot does not move when we press one of the direction keys

**Comment by ricardovj** [comment]
I have the exact same problem!

**Comment by na018** [comment]
restart and long waiting made the gui appear, and the error disappear. However, the bot does not move a bit on any key stroke.

**Comment by AleksandarPetrov** [comment]
If you are using the CLI interface make sure you're using the letter keys, not the arrow keys. And that you type in the terminal that says  `Enter direction(a,w,s,d)-->` and that you press Enter afterwards.

**Comment by AleksandarPetrov** [comment]
On a second look, I seems you're following the workflow for DB18, please make sure to check the DB19/master19 version of the documentation. These commands are now run from the duckietown shell and are much simplified.

**Comment by afdaniele** [comment]
@AleksandarPetrov can we close this?
