### ISSUE TITLE
Selecting geographic area after running the command 'dts challenges evaluate'

### ISSUE THREAD

**Issue by rizavelioglu** [duckietown/duckietown-shell-commands#117]
After running the command "dts challenges evaluate --challenge aido2-LF-sim-validation-offseason" I was asked to choose the geographic area but how am I supposed to give the input? Tried for example "8. Europe", "8", "8.", "Europe", "8. Europe" but didn't work out.

**Comment by AndreaCensi** [comment]
What program asked you exactly?

**Comment by rizavelioglu** [comment]
![Screenshot from 2019-07-11 23-45-39](https://user-images.githubusercontent.com/40141130/61087650-82bb1a00-a436-11e9-9ae8-52cc707bd3c7.png)

**Comment by rizavelioglu** [comment]
The issue still exists. When I run the command `dts challenges submit` I get the above question
