### ISSUE TITLE
Error init_sd_card command 

### ISSUE THREAD

**Issue by LukyBo** [duckietown/duckietown-shell-commands#120]
After typing the init_sd_card command and the installation the following question appears:
"? This will erase the selected drive. Are you sure?"
After typing "yes" the following error appears. What can I do?

The selected drive "/dev/sdc1" was not found
We can't find "/dev/sdc1" in your system. Did you unplug the drive?

dts : Traceback (most recent call last):
: File "/home/sakul1308/.local/lib/python3.7/site-packages/dt_shell/init.py", line 48, in cli_main
: cli_main_()
: File "/home/sakul1308/.local/lib/python3.7/site-packages/dt_shell/init.py", line 126, in cli_main_
: shell.onecmd(cmdline)
: File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/cmd.py", line 217, in onecmd
: return func(arg)
: File "/home/sakul1308/.local/lib/python3.7/site-packages/dt_shell/cli.py", line 413, in
: do_command_lam = lambda s, w: do_command(klass, s, w)
: File "/home/sakul1308/.local/lib/python3.7/site-packages/dt_shell/dt_command_abs.py", line 53, in do_command
: cls.command(shell, args)
: File "/home/sakul1308/.dt-shell/commands/init_sd_card/command.py", line 215, in command
: step2function[step_name](shell, parsed)
: File "/home/sakul1308/.dt-shell/commands/init_sd_card/command.py", line 289, in step_flash
: start_command_in_subprocess(script_cmd, env)
: File "/home/sakul1308/.dt-shell/commands/utils/cli_utils.py", line 30, in start_command_in_subprocess
: raise Exception(msg)
: Exception: Error occurred while running /bin/bash /home/sakul1308/.dt-shell/commands/init_sd_card/init_sd_card.sh, please check and retry (1).

dts : If you think this is a bug, please report that you are using:
:
: duckietown-shell-commands: 4.0.24
: duckietown-challenges: 4.0.30
: python: "3.7.4 (default, Jul 12 2019, 20:57:46) \n[GCC 5.4.0 20160609]"
: duckietown-shell: 4.0.24
: encodings:
: stdout: UTF-8
: stderr: UTF-8
: locale: UTF-8

**Comment by AleksandarPetrov** [comment]
@LukyBo Are you entering `/dev/sdc` when asked `Type the name of your device (include the '/dev' part)`?
And do you get the error above immediately after confirming or it takes some time? Can you check if you actually have this drive and if it is mounted?

**Comment by LukyBo** [comment]
Yes I've entered it and checked it with another USB-Stick. Didn't work either. 
I get the Error immediately after answering "? This will erase the selected drive. Are you sure?" with "y"


![Bildschirmfoto vom 2019-08-09 16-03-42](https://user-images.githubusercontent.com/53741700/62784673-4fb08880-babf-11e9-87b1-22e719d8ff89.png)

**Comment by AleksandarPetrov** [comment]
Hmm that is strange... @afdaniele can this have anything to do with the recent updates in `init_sd_card`?

**Comment by afdaniele** [comment]
@AleksandarPetrov I don't think so.
@LukyBo what operating system are you using. If Ubuntu, can you post the output of `cat /etc/lsb-release`?

**Comment by afdaniele** [comment]
It is very weird that `sdc1` appears to be of type `vfat`

**Comment by LukyBo** [comment]
Im using the newest version of Ubuntu:
![Bildschirmfoto vom 2019-08-12 14-20-33](https://user-images.githubusercontent.com/53741700/62864608-7d3e4180-bd0c-11e9-8edc-7bf32d3a48e9.png)

**Comment by LukyBo** [comment]
No I have initiated a folder release of the memory in the local network. 
Now there is a "bad archive" error. What would you recommend to do? Working with another version of Ubuntu? 
![Bildschirmfoto vom 2019-08-12 16-43-41](https://user-images.githubusercontent.com/53741700/62873961-a23caf80-bd20-11e9-9fa6-6dd2d30626a6.png)

**Comment by afdaniele** [comment]
No, I'm using the same version of Ubuntu and everything works on my side.
Can you share the entire Traceback of the error above?

**Comment by LukyBo** [comment]
Could the reason be that I didn't install a necessary package? Maybe it's a very trivial mistake.
![Bildschirmfoto vom 2019-08-12 17-17-32](https://user-images.githubusercontent.com/53741700/62876571-838ce780-bd25-11e9-93a4-c20ea1598739.png)

I'm using Ubuntu for the first time and I'm still very inexperienced.

**Comment by afdaniele** [comment]
Do `rm /tmp/duckietown/hypriotos-rpi-*` and then try again.

**Comment by LukyBo** [comment]
Did not work. It does not find the directory 
![Bildschirmfoto vom 2019-08-14 10-44-17](https://user-images.githubusercontent.com/53741700/63007305-ac75bf80-be80-11e9-856c-3728ab1b3cc9.png)

**Comment by LukyBo** [comment]
The error above occured. Then I typed: rm /tmp/duckietown/hypriotos-rpi-v1.9.0.img.zip
and tried it again with: dts init_sd_card  --hostname duckiebot
Do you recommend to reinstall Ubuntu? Try it with another computer? Do I have to change to hostname? How can I change the hostname? 

![grafik](https://user-images.githubusercontent.com/53741700/64343061-1bf84e00-cfec-11e9-8f03-51b51dd33d3e.png)
![grafik](https://user-images.githubusercontent.com/53741700/64343312-9c1eb380-cfec-11e9-81e5-e5a468f0128e.png)
![grafik](https://user-images.githubusercontent.com/53741700/64343355-b2c50a80-cfec-11e9-9c9a-7633db7b0a00.png)

**Comment by LukyBo** [comment]
I changed the terminal language to english and uninstalled docker-compose and reinstalled it via https://docs.docker.com/compose/install/#alternative-install-options. Now the init_sd_card command works!
