### ISSUE TITLE
Unknown syntax for any command

### ISSUE THREAD

**Issue by ssnirgudkar** [duckietown/duckietown-shell-commands#122]
Hi,
I have installed 'Windows Subsystem for Linux (WSL)' on my Windows 10 laptop. I have installed Ubuntu 18.04 version as part of it.
Then I followed instructions from 'https://docs.duckietown.org/DT19/opmanual_duckiebot/out/laptop_setup.html' corresponding to section 1.3.
The docker gave me some trouble. But I went ahead without fixing it and installed duckietown shell.
The dts command was okay and produced 'INFO:dts:duckietown-shell 4.0.26' along with other text.
However, if I give any command at dts prompt, it gives me error 'Unknown syntax: <command name>'.
How should I fix this problem?
-Shailesh

**Comment by liampaull** [comment]
Can you paste the entire output please? By the way Windows is not officially supported.

**Comment by ssnirgudkar** [comment]
Here it is -
--------------------------------------------------------------------------------------------------------
snirgudkar@Feynmann:~$ dts
INFO:dts:duckietown-shell 4.0.26

dts :  Problems with a command?
    :
    :  Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :
    :  Troubleshooting:
    :
    :  - If some commands update fail, delete ~/.dt-shell/commands
    :
    :  - To reset the shell to "factory settings", delete ~/.dt-shell
    :
    :    (Note: you will have to re-configure.)
INFO:duckietown-challenges:duckietown-challenges 4.0.30
INFO:dts:duckietown-shell-commands 4.0.41
Welcome to the Duckietown Shell (4.0.26).

Type "help" or "?" to list commands.


dt> dts tok set
*** Unknown syntax: dts tok set

dt> help

Documented commands (type help <topic>):
========================================
challenges  duckiebot  help          logs             uninstall
commands    exit       init_sd_card  start_gui_tools  update
docs        hatchery   install       tok              version


dt> dts start_gui_tools
*** Unknown syntax: dts start_gui_tools
-------------------------------------------------------------------------------------------

I know that Windows is not supported. That's why I installed WSL (Windows Subsystem For Linux). Isn't WSL also not supported?

**Comment by afdaniele** [comment]
WSL is not officially supported, but we can try to help.

**Comment by ssnirgudkar** [comment]
Yes, that will be much appreciated. Do you need any other information from me?

**Comment by liampaull** [comment]
once you are in the shell you don't have to write `dts` anymore. `dts` is a shorthand if you don't want to enter the shell.

**Comment by ssnirgudkar** [comment]
Thank you, your suggestion worked for me. That is once I am in dts shell, merely giving docs or other commands worked.
