### ISSUE TITLE
terminal language

### ISSUE THREAD

**Issue by afdaniele** [duckietown/duckietown-shell-commands#126]
Some commands (e.g., `init_sd_card`) fail when the terminal is in a language different than English. Some steps require fetching info from terminal output (e.g., from `fdisk`) so changing the language would break the regex matches.

Check the language and warn if it is not English, or change it on the fly if possible.

**Comment by jasonhu5** [comment]
@afdaniele is this still pending action?

**Comment by afdaniele** [comment]
This is not an issue anymore, we simplified `init_sd_card` and moved all CLI output parsing to developer-only commands where English terminals are guaranteed.
