### ISSUE TITLE
daffy stack for init_sd_card has useless images

### ISSUE THREAD

**Issue by AmaurX** [duckietown/duckietown-shell-commands#127]
@AndreaCensi @afdaniele @liampaull 
There are parts of the daffy stack that are loaded by default, making the flash slower, making the boot slower, and cluttering the sd card for nothing.

List of the files that should be removed from the daffy stack imo:

- DT18_02_others.yaml : https://github.com/duckietown/duckietown-shell-commands/blob/master/init_sd_card/stacks/daffy/DT18_02_others.yaml --> rpi-python-camera:master18 
- https://github.com/duckietown/duckietown-shell-commands/blob/master/init_sd_card/stacks/daffy/DT18_04_camera.yaml --> at least the camera one. I dont know about the web thing

For info, this is the (trimmed) output when flshing with daffy.

```INFO:dts:Pulling portainer/portainer:linux-arm
INFO:dts:Pulling v2tec/watchtower:armhf-latest
INFO:dts:Pulling duckietown/rpi-simple-server:master18
INFO:dts:Pulling duckietown/rpi-health:master18
INFO:dts:Pulling duckietown/rpi-duckiebot-online:master18
INFO:dts:Pulling duckietown/rpi-duckiebot-loader:master18
INFO:dts:Pulling duckietown/rpi-python-picamera:master18
INFO:dts:Pulling duckietown/dt-duckiebot-interface:daffy
INFO:dts:Pulling duckietown/dt-car-interface:daffy
INFO:dts:Pulling duckietown/dt-core:daffy
INFO:dts:Pulling duckietown/dt-duckiebot-dashboard:daffy
INFO:dts:Pulling duckietown/dt-rosbridge-websocket:daffy
```

Also, we should rename those files so that stuff doesnt show up as DT18 when it is actually daffy

**Comment by AndreaCensi** [comment]
The small picamera stuff was used once as part of the initialization procedure. A way to test the camera without loading the big ROS containers.

What is the impact on the size of the SD card?

If it is small, then just leave them there. Otherwise you might break things you might not know they are there.

**Comment by liampaull** [comment]
leave for now

**Comment by afdaniele** [comment]
@AmaurX can you branch out those that are still master19 and call them daffy?
I'll add them to Jenkins once done.

**Comment by AmaurX** [comment]
@afdaniele I don't understand what you mean

**Comment by AmaurX** [comment]
@AndreaCensi  
`duckietown/rpi-python-picamera:master18` is 250MB, it is probably the only one we dont (usually) use. So indeed it is not huge, but not negligible either

**Comment by AmaurX** [comment]
@AndreaCensi Also, as a way to test the camera, it should now be working by default on start up, so people just need a rqt_image_view or the dashboard. I dont think it is longer necessary and even more, since we are not maintaining it, it should go IMO
