### ISSUE TITLE
SSH to bot requires password even with DT18 pub/private key + config installed

### ISSUE THREAD

**Issue by johnbmcd** [duckietown/duckietown-shell-commands#131]
**Issue:** when sshing to duckiebot you are asked for a password even though you have the DT18 priv/pub key + config in .ssh
**Symptom:** ssh client still ask for password and prints following warning
"sign_and_send_pubkey: signing failed: agent refused operation
duckie@quackbot1.local's password:"
**Cause:** private key is installed in user's .ssh folder with 664 permissions but 
-rw-rw-r--  1 john john 1675 Sep 13 15:43 DT18_key_00
**should have 600 permissions**
-rw------- 1 john john 1675 Sep 13 15:43 DT18_key_00

**Comment by liampaull** [comment]
thanks @johnbmcd we will fix

**Comment by afdaniele** [comment]
Fixed!
