### ISSUE TITLE
Running init_sd_card with --steps does not prompt user for device name

### ISSUE THREAD

**Issue by sebgiles** [duckietown/duckietown-shell-commands#134]
to recreate:
run init_sd_card with `--steps flash`
then run init_sd_card with `--steps expand`
you will get `Exception: This only works assuming device ==`
unless you also add `--device \dev\xxx`

**Comment by AleksandarPetrov** [comment]
@sebgiles this is not a bug. That's how it's supposed to work. When you do all the steps, you're asked to select the device in the beginning, if you're skip the first steps, you need to explicitly supply it.
