### ISSUE TITLE
Flag for getting into  terminal for docker run commands

### ISSUE THREAD

**Issue by liampaull** [duckietown/duckietown-shell-commands#14]
It is a limitation for debugging that you can't overwrite the docker CMD and through the command line. A nice feature would be a flag to add `/bin/bash` at the end of the docker run.

**Comment by breandan** [comment]
When running an image where `CMD` is defined, you can either attach a shell with `docker exec` or pass a custom entrypoint to override it, like so: https://serverfault.com/a/594486

**Comment by liampaull** [comment]
yes I know but we lose that functionality by launching things with dts

**Comment by jasonhu5** [comment]
`dts` has an option now to specify the launch command with `--cmd` option.
