### ISSUE TITLE
dts command not working  

### ISSUE THREAD

**Issue by moaz-azam** [duckietown/duckietown-shell-commands#140]
INFO:dts:duckietown-shell 5.0.3

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)

dts :  You have not specified a Duckietown version. Please use:
    :          
    :          dts --set-version <version>
    :          
    :          where <version> = daffy, master19

dts :  If you think this is a bug, please report that you are using:
    :  
    :  duckietown-shell: 5.0.3
    :  encodings:
    :    locale: UTF-8
    :    stderr: UTF-8
    :    stdout: UTF-8
    :  python: "3.7.3 (default, Oct  7 2019, 12:56:13) \n[GCC 8.3.0]"
moaz@moaz-HP-ProBook-450-G3:~$ which dts
/home/moaz/.local/bin/dts
moaz@moaz-HP-ProBook-450-G3:~$ dts
INFO:dts:duckietown-shell 5.0.3

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)

dts :  You have not specified a Duckietown version. Please use:
    :          
    :          dts --set-version <version>
    :          
    :          where <version> = daffy, master19

dts :  If you think this is a bug, please report that you are using:
    :  
    :  duckietown-shell: 5.0.3
    :  encodings:
    :    locale: UTF-8
    :    stderr: UTF-8
    :    stdout: UTF-8
    :  python: "3.7.3 (default, Oct  7 2019, 12:56:13) \n[GCC 8.3.0]"

**Comment by afdaniele** [comment]
@moaz-azam 
You need to specify which version of the shell you want to use.
You can run 
`dts --set-version master19` for `master19`,
OR
`dts --set-version daffy` for `daffy`.
