### ISSUE TITLE
duckietown shell update i

### ISSUE THREAD

**Issue by harisasif** [duckietown/duckietown-shell-commands#147]
dts :  duckietown-shell-commands requires Python 3.6 and later.
    :  Detected 2.7.15 (default, Aug 16 2018, 14:17:09) 
    :  [GCC 6.4.0].

dts :  Please report that you are using:
    :  
    :  duckietown-shell: 3.0.30
    :  python: "2.7.15 (default, Aug 16 2018, 14:17:09) \n[GCC 6.4.0]"

I am getting this issue!
need to update!

**Comment by jasonhu5** [comment]
It's python version that seems to require an update
