### ISSUE TITLE
How to delete ~/.dt-shell/commands

### ISSUE THREAD

**Issue by notSoTechnical** [duckietown/duckietown-shell-commands#148]
> notsotechnical@notsotechnical-MacBookPro:~$ **dts tok set**
> INFO:dts:duckietown-shell 5.1.2
> 
> dts :  Problems with a command?
>     :  
>     :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
>     :  
>     :      Troubleshooting:
>     :  
>     :      - If some commands update fail, delete ~/.dt-shell/commands
>     :  
>     :      - To reset the shell to "factory settings", delete ~/.dt-shell
>     :  
>     :        (Note: you will have to re-configure.)
> 
> dts :  You have not specified a Duckietown version. Please use:
>     :  
>     :          dts --set-version <version>
>     :  
>     :          where <version> = daffy, master19
> 
> dts :  If you think this is a bug, please report that you are using:
>     :  
>     :  commands-version: null
>     :  duckietown-shell: 5.1.2
>     :  encodings:
>     :    locale: UTF-8
>     :    stderr: UTF-8
>     :    stdout: UTF-8
>     :  python: "3.6.8 (default, Oct  7 2019, 12:59:55) \n[GCC 8.3.0]"
> 
>

**Comment by AleksandarPetrov** [comment]
@notSoTechnical I am not sure what is the exact problem you have but perhaps this answers it:

> dts : You have not specified a Duckietown version. Please use:
> :
> : dts --set-version
> :
> : where = daffy, master19

If you still want to delete your commands, just run `rm -r ~/.dt-shell/commands`

**Comment by rserafin** [comment]
I also have the same problem, when I write command: rm -r ~/.dt-shell/commands, I have result: rm: cannot remove '/home/radoslaw/.dt-shell/commands': No such file or directory

**Comment by rserafin** [comment]
@gibernas could you see this error?

radoslaw@Ubuntu18:~/.dt-shell$ dts
INFO:dts:duckietown-shell 5.1.2

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)

dts :  You have not specified a Duckietown version. Please use:
    :  
    :          dts --set-version <version>
    :  
    :          where <version> = daffy, master19

dts :  If you think this is a bug, please report that you are using:
    :  
    :  commands-version: null
    :  duckietown-shell: 5.1.2
    :  encodings:
    :    locale: UTF-8
    :    stderr: UTF-8
    :    stdout: UTF-8
    :  python: "3.6.9 (default, Nov  7 2019, 10:44:02) \n[GCC 8.3.0]"
radoslaw@Ubuntu18:~/.dt-shell$ ls -la
total 12
drwxr-xr-x  2 radoslaw radoslaw 4096 lis 29 00:32 .
drwxr-xr-x 15 radoslaw radoslaw 4096 lis 29 00:29 ..
-rw-r--r--  1 radoslaw radoslaw   63 lis 29 00:29 config.yaml
radoslaw@Ubuntu18:~/.dt-shell$ rm -r ~/.dt-shell/commands
rm: cannot remove '/home/radoslaw/.dt-shell/commands': No such file or directory
radoslaw@Ubuntu18:~/.dt-shell$ 

I also have the same problem, when I write command: rm -r ~/.dt-shell/commands, I have result: rm: cannot remove '/home/radoslaw/.dt-shell/commands': No such file or directory

**Comment by gibernas** [comment]
The commands now get saved to `~/.dt-shell/commands-multi/*`, so there is a misprint. But your problem is that you did not set the commands version with `dts —set-version`, so you did not download the commands yet.
