### ISSUE TITLE
Error with "dts duckiebot calibrate_extrinsics [DUCKIEBOT_NAME]"

### ISSUE THREAD

**Issue by Eduardo-az** [duckietown/duckietown-shell-commands#151]
dts :  Traceback (most recent call last):
    :    File "/home/eduardo/.local/lib/python3.6/site-packages/dt_shell/main.py", line 38, in cli_main
    :      cli_main_()
    :    File "/home/eduardo/.local/lib/python3.6/site-packages/dt_shell/main.py", line 175, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python3.6/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/eduardo/.local/lib/python3.6/site-packages/dt_shell/cli.py", line 287, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/eduardo/.local/lib/python3.6/site-packages/dt_shell/dt_command_abs.py", line 42, in do_command
    :      cls.commands[word], shell, " ".join(parts[1:])
    :    File "/home/eduardo/.local/lib/python3.6/site-packages/dt_shell/dt_command_abs.py", line 50, in do_command
    :      cls.command(shell, args)
    :    File "/home/eduardo/.dt-shell/commands-multi/master19/duckiebot/calibrate_extrinsics/command.py", line 72, in command
    :      environment=env)
    :    File "/home/eduardo/.local/lib/python3.6/site-packages/docker/models/containers.py", line 832, in run
    :      container, exit_status, command, image, out
    :  docker.errors.ContainerError: Command '/bin/bash -c 'rosrun complete_image_pipeline calibrate_extrinsics -o /data/out-calibrate-extrinsics-daffy-20191113000000 > /data/out-calibrate-extrinsics-daffy-20191113000000.log'' in image 'duckietown/rpi-duckiebot-base:master19' returned non-zero exit status 2: b'rosrun complete_image_pipeline calibrate_extrinsics|  has_logger.py:12   - info           | \x1b[32m\x1b[32m\x1b[32mTaking a picture. Say cheese!\x1b[0m\x1b[0m\x1b[0m\nrosrun complete_image_pipeline calibrate_extrinsics|  has_logger.py:12   - info           | \x1b[32m\x1b[32m\x1b[32mPicture taken: (480, 640, 3) \x1b[0m\x1b[0m\x1b[0m\nrosrun complete_image_pipeline calibrate_extrinsics|  has_logger.py:12   - info           | \x1b[32m\x1b[32m\x1b[32mResized to: (480, 640, 3) \x1b[0m\x1b[0m\x1b[0m\n             DT|configuration.py:73   - get_homography_info_config_file| \x1b[32m\x1b[32m\x1b[32mUsing filename /data/config/calibrations/camera_extrinsic/default.yaml\x1b[0m\x1b[0m\x1b[0m\n             DT|ground_projection_interface.py:204  - load_board_info| \x1b[32m\x1b[32m\x1b[32mLoaded checkerboard parameters\x1b[0m\x1b[0m\x1b[0m\n             DT|ground_projection_interface.py:71   - estimate_homography| \x1b[32m\x1b[32m\x1b[32mboard: \n {\'square_size\': 0.031, \'height\': 5, \'width\': 7, \'y_offset\': 0.093, \'x_offset\': 0.191, \'offset\': array([ 0.191, -0.093]), \'size\': (7, 5)}\x1b[0m\x1b[0m\x1b[0m\n             DT|  file_utils.py:34   - write_data_to_file| \x1b[35m\x1b[35m\x1b[35mWritten to: /data/out-calibrate-extrinsics-daffy-20191113000000/step00-bgr.jpg\x1b[0m\x1b[0m\x1b[0m\n             DT|  file_utils.py:34   - write_data_to_file| \x1b[35m\x1b[35m\x1b[35mWritten to: /data/out-calibrate-extrinsics-daffy-20191113000000/step01-bgr_rectified.jpg\x1b[0m\x1b[0m\x1b[0m\n             DT|  file_utils.py:34   - write_data_to_file| \x1b[35m\x1b[35m\x1b[35mWritten to: /data/out-calibrate-extrinsics-daffy-20191113000000/step02-rectified_full_ratio_auto.jpg\x1b[0m\x1b[0m\x1b[0m\n             DT|  file_utils.py:34   - write_data_to_file| \x1b[35m\x1b[35m\x1b[35mWritten to: /data/out-calibrate-extrinsics-daffy-20191113000000/all.jpg\x1b[0m\x1b[0m\x1b[0m\n       quickapp|script_utils.py:60   - wrap_script_entry_point_noexit| \x1b[31m\x1b[31m\x1b[31mTraceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/decent_params/utils/script_utils.py", line 49, in wrap_script_entry_point_noexit\n    ret = function(args)\n  File "/usr/local/lib/python2.7/dist-packages/quickapp/quick_app_base.py", line 167, in main\n    ret = self.go()\n  File "/home/software/catkin_ws/src/10-lane-control/complete_image_pipeline/include/complete_image_pipeline/calibrate_extrinsics.py", line 86, in go\n    raise Exception(result.error)\nException: findChessboardCorners failed (len(corners) == 33)\n\x1b[0m\x1b[0m\x1b[0m\n     rospy.core|        core.py:454  - signal_shutdown| \x1b[32m\x1b[32m\x1b[32msignal_shutdown [atexit]\x1b[0m\x1b[0m\x1b[0m\n'

**Comment by gibernas** [comment]
What is the version of the commands you are using, and what is the version of the software in your Duckiebot?

Also, from the trace back it seems the corners of the calibration pattern are not visible, could this be the case?

**Comment by Eduardo-az** [comment]
The version of duckietown-shell is 5.1.2 and the version of the software in my duckiebot is hypriotos v7

**Comment by liampaull** [comment]
This error is created when calibration pattern is not visible. Take a look at the raw camera image and make sure that the checkerboard pattern is visible.
