### ISSUE TITLE
Error with Wheel Calibration

### ISSUE THREAD

**Issue by Eduardo-az** [duckietown/duckietown-shell-commands#157]
root@daffy:/home/software# rosservice call /daffy/inverse_kinematics_node /set_trim -- 0.00
ERROR: Service [/daffy/inverse_kinematics_node] is not available.

**Comment by AmaurX** [comment]
This is not the proper way to create an issue @Eduardo-az ...
Please provide :
- Context
- Version of the containers (are you sure you pulled latest version)
- What command you ran to launch the container
- Is your duckiebot named "daffy" ?
- Where in the docs did you see that?
- Are you following the right instructions ?

Bottom line, if you want help, this is the best way not to get it.

**Comment by hosnerm** [comment]
@Eduardo-az i think you probably use a wrong documentation. In the daffy branch, the `inverse_kinematics_node` is replaced by the `kinematics_node`. Also please look up the syntax of the whole command in the documentation. Try replacing it and you should be good to go.
