### ISSUE TITLE
init_sd_card and docker - please add a note

### ISSUE THREAD

**Issue by DELTAJoSch** [duckietown/duckietown-shell-commands#161]
There is an issue with docker when running init_sd_card:
If you do not change the dns server in /etc/resolv.conf to 8.8.8.8 (google) docker will fail to connect. After having had this problem and having spent multiple hours on this issue I would like to ask if it would be possible to add a note about this issue for first time users.

**Comment by AleksandarPetrov** [comment]
@DELTAJoSch this sounds like a very specific issue, have you experienced it in different networks, or in only one?

**Comment by DELTAJoSch** [comment]
Yes, it has happened in multiple networks. It happened at school and at home. There was a nameserver set in /etc/resolv.conf (I didn't change it previously). After changing /etc/resolv.conf to the following:
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver WHATEVERTHENAMESERVERWASTHATDIDNTWORK

it now appears to be working.

I found out about the solution thanks to [this link.](https://github.com/moby/moby/issues/22635#issuecomment-260063252)

I think my school and I are using the same provider (Austria, provider is A1). Maybe it has something to do with that?
