### ISSUE TITLE
Error in Unit C-11 Taking and verifying a log

### ISSUE THREAD

**Issue by Eduardo-az** [duckietown/duckietown-shell-commands#163]
I'm triyng to record a log by make log-full-docker but it threw error opening file /logs/
![log](https://user-images.githubusercontent.com/56844523/72095853-de2f6d00-32de-11ea-9901-12fa39c1a5f0.png)
Why if I've made mkdir /data/logs now it attempts to open files at the different path?

**Comment by liampaull** [comment]
this looks like a bug that should get fixed. I will look into it.
