### ISSUE TITLE
Motors not moving

### ISSUE THREAD

**Issue by badz41** [duckietown/duckietown-shell-commands#167]
dts :  Traceback (most recent call last):
    :    File "/home/badz41/.local/lib/python3.6/site-packages/dt_shell/main.py", line 38, in cli_main
    :      cli_main_()
    :    File "/home/badz41/.local/lib/python3.6/site-packages/dt_shell/main.py", line 175, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python3.6/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/badz41/.local/lib/python3.6/site-packages/dt_shell/cli.py", line 287, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/badz41/.local/lib/python3.6/site-packages/dt_shell/dt_command_abs.py", line 42, in do_command
    :      cls.commands[word], shell, " ".join(parts[1:])
    :    File "/home/badz41/.local/lib/python3.6/site-packages/dt_shell/dt_command_abs.py", line 50, in do_command
    :      cls.command(shell, args)
    :    File "/home/badz41/.dt-shell/commands-multi/master19/duckiebot/keyboard_control/command.py", line 44, in command
    :      run_gui_controller(parsed_args.hostname, parsed_args.image, duckiebot_ip, network_mode)
    :    File "/home/badz41/.dt-shell/commands-multi/master19/duckiebot/keyboard_control/command.py", line 102, in run_gui_controller
    :      start_command_in_subprocess(cmd)
    :    File "/home/badz41/.dt-shell/commands-multi/master19/utils/cli_utils.py", line 30, in start_command_in_subprocess
    :      raise Exception(msg)
    :  Exception: Error occurred while running docker attach joystick_gui_robotik, please check and retry (1).

dts :  If you think this is a bug, please report that you are using:
    :  
    :  duckietown-challenges: 5.1.4
    :  duckietown-shell-commands: 4.0.44
    :  python: "3.6.8 (default, Aug 20 2019, 17:12:48) \n[GCC 8.3.0]"
    :  duckietown-shell: 5.1.6
    :  commands-version: master19
    :  encodings:
    :    stdout: UTF-8
    :    stderr: UTF-8
    :    locale: UTF-8

**Comment by liampaull** [comment]
this usually means that the joystick controller is crashing. Can you go into portainer and look at the log for the joystick controller and post here?

**Comment by badz41** [comment]
Issue solved the joystick was not running
