### ISSUE TITLE
Camera Calibration

### ISSUE THREAD

**Issue by badz41** [duckietown/duckietown-shell-commands#168]
During the extrinsic calibration of the camera we always acquired this data we want to know if this data is good.
![Screenshot from 2020-02-12 06-31-27](https://user-images.githubusercontent.com/60834818/74245751-7675a300-4d1e-11ea-9a86-e624a05aaa61.png)
![Screenshot from 2020-02-12 06-31-05](https://user-images.githubusercontent.com/60834818/74245755-783f6680-4d1e-11ea-8ce0-4fc6013aa43a.png)

**Comment by liampaull** [comment]
it looks good!
