### ISSUE TITLE
dts problem

### ISSUE THREAD

**Issue by Witcher69** [duckietown/duckietown-shell-commands#169]
I have a problem when I try to run dts.
pietacer@pietacer-Aspire-E1-572:~$ dts commands
INFO:dts:duckietown-shell 5.1.6

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)
INFO:dts:Commands version: daffy,
WARNING:dts:I cannot find the command path /home/pietacer/.dt-shell/commands-multi/daffy,
INFO:dts:Downloading commands in /home/pietacer/.dt-shell/commands-multi/daffy, ...

dts :  Traceback (most recent call last):
    :    File "/home/pietacer/.local/lib/python3.6/site-packages/dt_shell/main.py", line 38, in cli_main
    :      cli_main_()
    :    File "/home/pietacer/.local/lib/python3.6/site-packages/dt_shell/main.py", line 170, in cli_main_
    :      shell = DTShell(shell_config, commands_info)
    :    File "/home/pietacer/.local/lib/python3.6/site-packages/dt_shell/cli.py", line 118, in __init__
    :      _init_commands(commands_path, self.repo_info)
    :    File "/home/pietacer/.local/lib/python3.6/site-packages/dt_shell/commands_.py", line 31, in _init_commands
    :      commands_path
    :    File "/home/pietacer/.local/lib/python3.6/site-packages/dt_shell/utils.py", line 121, in run_cmd
    :      raise RuntimeError(msg)
    :  RuntimeError: The command ['git', 'clone', '-b', 'daffy,', '--recurse-submodules', 'https://github.com/duckietown/duckietown-shell-commands', '/home/pietacer/.dt-shell/commands-multi/daffy,'] failed with exit code 128.
    :  Error:
    :  None

dts :  If you think this is a bug, please report that you are using:
    :  
    :  commands-version: daffy,
    :  duckietown-shell: 5.1.6
    :  encodings:
    :    locale: UTF-8
    :    stderr: UTF-8
    :    stdout: UTF-8
    :  python: "3.6.9 (default, Nov  7 2019, 10:44:02) \n[GCC 8.3.0]"

**Comment by gibernas** [comment]
Git clone is failing, are you sure your git installation is fine? Or that you don't local changes in the commands folder?

**Comment by liampaull** [comment]
@Witcher69 any update here or else we should close.
