### ISSUE TITLE
dts command update

### ISSUE THREAD

**Issue by badz41** [duckietown/duckietown-shell-commands#170]
> $ dts                                                                        
INFO:dts:duckietown-shell 5.1.6

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)
INFO:dts:Commands version: master19
INFO:dts:looking at /home/badz41/.dt-shell/commands-multi/master19
INFO:duckietown-challenges:duckietown-challenges 5.1.4
uINFO:zj:zuper-ipce 5.2.0
INFO:zuper-typing:zuper-typing 5.1.1
INFO:zuper-commons:zuper-commons 5.0.9
[INFO:dts:duckietown-shell-commands 4.0.44
Welcome to the Duckietown Shell (5.1.6).

Type "help" or "?" to list commands.

(Cmd) update

dts :  Traceback (most recent call last):
    :    File "/home/badz41/.local/lib/python3.6/site-packages/dt_shell/main.py", line 38, in cli_main
    :      cli_main_()
    :    File "/home/badz41/.local/lib/python3.6/site-packages/dt_shell/main.py", line 177, in cli_main_
    :      shell.cmdloop()
    :    File "/usr/lib/python3.6/cmd.py", line 138, in cmdloop
    :      stop = self.onecmd(line)
    :    File "/usr/lib/python3.6/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/badz41/.local/lib/python3.6/site-packages/dt_shell/cli.py", line 287, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/badz41/.local/lib/python3.6/site-packages/dt_shell/dt_command_abs.py", line 59, in do_command
    :      cls.command(shell, args)
    :    File "/home/badz41/.dt-shell/commands-multi/master19/update/command.py", line 12, in command
    :      if shell.commands_path_leave_alone:
    :  AttributeError: 'DTShell' object has no attribute 'commands_path_leave_alone'

dts :  If you think this is a bug, please report that you are using:
    :  
    :  duckietown-challenges: 5.1.4
    :  duckietown-shell-commands: 4.0.44
    :  python: "3.6.8 (default, Aug 20 2019, 17:12:48) \n[GCC 8.3.0]"
    :  duckietown-shell: 5.1.6
    :  commands-version: master19
    :  encodings:
    :    stdout: UTF-8
    :    stderr: UTF-8
    :    locale: UTF-8

**Comment by liampaull** [comment]
I suggest to remove the `~/.dt-shell` folder and reinstall with pip.
