### ISSUE TITLE
joystick error

### ISSUE THREAD

**Issue by badz41** [duckietown/duckietown-shell-commands#171]
dts :  Traceback (most recent call last):
    :    File "/home/badz41/.local/lib/python3.6/site-packages/dt_shell/main.py", line 38, in cli_main
    :      cli_main_()
    :    File "/home/badz41/.local/lib/python3.6/site-packages/dt_shell/main.py", line 175, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python3.6/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/badz41/.local/lib/python3.6/site-packages/dt_shell/cli.py", line 287, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/badz41/.local/lib/python3.6/site-packages/dt_shell/dt_command_abs.py", line 42, in do_command
    :      cls.commands[word], shell, " ".join(parts[1:])
    :    File "/home/badz41/.local/lib/python3.6/site-packages/dt_shell/dt_command_abs.py", line 50, in do_command
    :      cls.command(shell, args)
    :    File "/home/badz41/.dt-shell/commands-multi/master19/duckiebot/keyboard_control/command.py", line 44, in command
    :      run_gui_controller(parsed_args.hostname, parsed_args.image, duckiebot_ip, network_mode)
    :    File "/home/badz41/.dt-shell/commands-multi/master19/duckiebot/keyboard_control/command.py", line 102, in run_gui_controller
    :      start_command_in_subprocess(cmd)
    :    File "/home/badz41/.dt-shell/commands-multi/master19/utils/cli_utils.py", line 30, in start_command_in_subprocess
    :      raise Exception(msg)
    :  Exception: Error occurred while running docker attach joystick_gui_robotik, please check and retry (1).

dts :  If you think this is a bug, please report that you are using:
    :  
    :  duckietown-challenges: 5.1.4
    :  duckietown-shell-commands: 4.0.44
    :  python: "3.6.8 (default, Oct  7 2019, 12:59:55) \n[GCC 8.3.0]"
    :  duckietown-shell: 5.1.6
    :  commands-version: master19
    :  encodings:
    :    stdout: UTF-8
    :    stderr: UTF-8
    :    locale: UTF-8

**Comment by liampaull** [comment]
is this the same issue as before?

**Comment by badz41** [comment]
> is this the same issue as before?

No, this happen when i quit the program and sometimes the joystick wont work

**Comment by liampaull** [comment]
@badz41 can you test this with the `daffy` version of the shell commands to see if it persists? to switch versions do `dts --set-version daffy`.

**Comment by jasonhu5** [comment]
Not updated for some time. Closing for now

**Comment by gaetanotorella** [comment]
I have the same problem on DB19

commands-version: daffy
dt-authentication-daffy: 0.1.16
dt-data-api-daffy: 1.2.0
duckietown-docker-utils-daffy: 6.1.1
duckietown-shell: 5.5.13
duckietown-shell-commands: 5.4.5
encodings:
  locale: UTF-8
  stderr: utf-8
  stdout: utf-8
python: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
