### ISSUE TITLE
Problem with the shell launch

### ISSUE THREAD

**Issue by federica01freddy** [duckietown/duckietown-shell-commands#173]
Hello I have this problem when I try to use DuckieTown shell. I have python 2.7 and python 3.6 and also if I disinstall 2.7, I continue to have this issue.

INFO:dts:duckietown-shell 3.0.30
dts :  Problems with a command?
    :  
    :  Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :  Troubleshooting:
    :  
    :  - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :  - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :    (Note: you will have to re-configure.)

There is an updated duckietown-shell available.

  You have: 3.0.30

 available: 5.1.6 

You should update the shell using `pip`.        
        
        
Waiting 3 seconds to give you time to read the message.

dts :  duckietown-shell-commands requires Python 3.6 and later.
    :  Detected 2.7.15 (default, Aug 16 2018, 14:17:09) 
    :  [GCC 6.4.0].

dts :  Please report that you are using:
    :  
    :  duckietown-shell: 3.0.30
    :  python: "2.7.15 (default, Aug 16 2018, 14:17:09) \n[GCC 6.4.0]"

**Comment by lujobi** [comment]
did you install the shell with `pip3 install --no-cache-dir --user -U duckietown-shell` or using `pip install` ?

It seems to be using python 2.7 to run the shell.

**Comment by federica01freddy** [comment]
I installed with pip3

**Comment by liampaull** [comment]
I would reinstall the shell from scratch. It is definitely a python 2.7 problem.

**Comment by federica01freddy** [comment]
I resolve this problem removing python 2.7 but now I have this other issue:
freddy@freddy-HP-ENVY-Notebook:~$ dts
INFO:dts:duckietown-shell 5.1.6

dts :  Problems with a command?
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :      Troubleshooting:
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :        (Note: you will have to re-configure.)

dts :  Traceback (most recent call last):
    :    File "/home/freddy/.local/lib/python3.6/site-packages/dt_shell/main.py", line 127, in cli_main_
    :      shell_config = read_shell_config()
    :    File "/home/freddy/.local/lib/python3.6/site-packages/dt_shell/config.py", line 56, in read_shell_config
    :      return read_shell_config_from_file(config_file)
    :    File "/home/freddy/.local/lib/python3.6/site-packages/dt_shell/config.py", line 87, in read_shell_config_from_file
    :      raise ConfigNotPresent(fn)
    :  dt_shell.exceptions.ConfigNotPresent: /home/freddy/.dt-shell/config.yaml
    :  
    :  During handling of the above exception, another exception occurred:
    :  
    :  Traceback (most recent call last):
    :    File "/home/freddy/.local/lib/python3.6/site-packages/dt_shell/main.py", line 38, in cli_main
    :      cli_main_()
    :    File "/home/freddy/.local/lib/python3.6/site-packages/dt_shell/main.py", line 133, in cli_main_
    :      write_shell_config(shell_config)
    :    File "/home/freddy/.local/lib/python3.6/site-packages/dt_shell/config.py", line 62, in write_shell_config
    :      write_shell_config_to_file(shell_config, config_file)
    :    File "/home/freddy/.local/lib/python3.6/site-packages/dt_shell/config.py", line 79, in write_shell_config_to_file
    :      with open(filename, "w") as f:
    :  PermissionError: [Errno 13] Permission denied: '/home/freddy/.dt-shell/config.yaml'
