### ISSUE TITLE
Extrinsic camera calibration 

### ISSUE THREAD

**Issue by Eduardo-az** [duckietown/duckietown-shell-commands#175]
During the extrinsic calibration of the camera, I've acquired these images, as you can see on the map reprojected on image it looks very clear and this software doesn't recognize the lines.
![extrinsics](https://user-images.githubusercontent.com/56844523/76906147-f97fa100-6868-11ea-8114-0abb2ca59671.png)

**Comment by liampaull** [comment]
One issue is that you put your robot on the left hand side of the road. The convention in Duckietown is that we drive on the right-hand side.

**Comment by liampaull** [comment]
@Eduardo-az any update on this? otherwise we should close.
