### ISSUE TITLE
dts report also docker client and engine versions

### ISSUE THREAD

**Issue by AleksandarPetrov** [duckietown/duckietown-shell-commands#179]
By using [this](https://docker-py.readthedocs.io/en/stable/client.html#docker.client.DockerClient.version), we can obtain and print the version of the Docker Client and Engine when running dts commands. Can be helpful for cases such as this: https://github.com/duckietown/duckietown-shell-commands/issues/178

The result can be something like:
```
INFO:duckietown-challenges:duckietown-challenges 5.1.5
INFO:zj:zuper-ipce 5.3.0
INFO:zuper-typing:zuper-typing 5.3.0
INFO:zuper-commons:zuper-commons 5.0.11
INFO:dts:duckietown-shell-commands 5.0.2
INFO:docker-client:19.03.8, API: 1.40
INFO:docker-engine:19.03.8, API: 1.40
```

**Comment by afdaniele** [comment]
Tracked here: https://ethidsc.atlassian.net/browse/DTSW-2432 (private link)
