### ISSUE TITLE
Error in dts fleet discover

### ISSUE THREAD

**Issue by afdaniele** [duckietown/duckietown-shell-commands#191]
![image](https://user-images.githubusercontent.com/22665009/88319456-d1ee8880-cce1-11ea-82f2-a5a1e8a86ca5.png)

**Comment by hristo-vrigazov** [comment]
So uhm I am getting the same thing, what should I do to fix this?

**Comment by afdaniele** [comment]
@hristo-vrigazov this was fixed in a development branch, it will be available mainstream in a few days.
