### ISSUE TITLE
Unknown syntax for dts fleet discover

### ISSUE THREAD

**Issue by hristo-vrigazov** [duckietown/duckietown-shell-commands#201]
So I flashed the card, and I started the Duckiebot (I see it started correctly, since I attached an HDMI to it). I also can ping the duckiebot, so it is visible in the network. However, I am getting an `Unknown syntax error` when I run the next step from the instructions here https://docs.duckietown.org/daffy/opmanual_duckiebot/out/setup_duckiebot.html:

```
λ hvrigazov [~/] at  master !?
→ dts fleet discover                                                                                                                                                                              [099b569]
INFO:dts:duckietown-shell 5.1.6

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)
INFO:dts:Commands version: master19
INFO:dts:looking at /home/hvrigazov/.dt-shell/commands-multi/master19
INFO:duckietown-challenges:duckietown-challenges 5.1.4
INFO:zj:zuper-ipce 5.2.0
INFO:zuper-typing:zuper-typing 5.1.1
INFO:zuper-commons:zuper-commons 5.0.9
INFO:dts:duckietown-shell-commands 4.0.44
*** Unknown syntax: fleet discover

```

**Comment by jasonhu5** [comment]
Hi! I think this is a *dts* version issue. 

As shown in your logs, the *dts* is using master19 version: **INFO:dts:Commands version: master19**. 
According to the [dts master19 commands repo](https://github.com/duckietown/duckietown-shell-commands/tree/master19), there is no *fleet* command available. You should also be able to verify this by `dts help`, which prints the set of available commands of the current version of dts.

For solution, I think you could try `dts --set-version daffy` and then `dts fleet discover`.

*fleet* commands should be available on the **daffy** version of dts, according to [this branch of the repo](https://github.com/duckietown/duckietown-shell-commands/tree/daffy).

**Comment by hristo-vrigazov** [comment]
Yep, that was it. It looks like it's not a problem that I flashed with master19, and running `dts fleet discover` with daffy, it still finds it. Thanks!
