### ISSUE TITLE
[Feature request] convenient way to start container

### ISSUE THREAD

**Issue by CourchesneA** [duckietown/duckietown-shell-commands#208]
As a student (and now as a developer), I sometime wanted to start a new container on the duckiebot. For instance, if I see that the `dt-duckiebot-interface` was not running due to some error, I would like to start it. However, it is hard to know / remember all the parameters that I need to pass to `docker run`. It would be useful to have some kind of alias, or a `dts` command to remember those for us. As of now, I refer to the _See what your Duckiebot sees_ page:

`docker -H DUCKIEBOT_NAME.local run --name duckiebot-interface -v /data:/data --privileged --network=host -dit --restart unless-stopped duckietown/dt-duckiebot-interface:daffy-arm32v7`

**Comment by jasonhu5** [comment]
The parameters are stored in config yaml files for `stack` commands. So it's possible to kill the container with docker stop/kill or from portainer, and start the stack containing that target container.

**Comment by jasonhu5** [comment]
It might still be an easy and interesting feature to implement, though. We just need to allow the `dts stack up` command to take some service names to run by docker-compose.

**Comment by afdaniele** [comment]
This is now possible thanks to the use of `dockertown` and the definition of a dockertown-compatible configuration in the `configurations.yaml` of each project.
Tracked here: https://ethidsc.atlassian.net/browse/DTSW-2430 (private link)
