### ISSUE TITLE
DTS install / python version

### ISSUE THREAD

**Issue by oooolga** [duckietown/duckietown-shell-commands#210]
I successfully installed DTS using pip3 commands.

> Successfully built duckietown-shell
Installing collected packages: duckietown-shell
  WARNING: The script dts is installed in '/Users/olgaluo/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed duckietown-shell-5.1.10

I added following lines to my _~/.bash_profile_ file
`PATH="/Users/olgaluo/Library/Python/3.8/bin:/Users/olgaluo/.local/bin:${PATH}"`
`export PATH`

However, when I try to run `dts` command I get the following error message:

> dts :  Problems with a command?
    :  
    :  Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :  Troubleshooting:
    :  
    :  - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :  - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :    (Note: you will have to re-configure.)

> There is an updated duckietown-shell available.
> 
>   You have: 3.0.30
> 
>  available: 5.1.10 
> 
> You should update the shell using `pip`.        
>         
>         
> Waiting 3 seconds to give you time to read the message.
> 
> dts :  duckietown-shell-commands requires Python 3.6 and later.
>     :  Detected 2.7.15 (default, Aug 16 2018, 14:17:09) 
>     :  [GCC 6.4.0].
> 
> dts :  Please report that you are using:
>     :  
>     :  duckietown-shell: 3.0.30
>     :  python: "2.7.15 (default, Aug 16 2018, 14:17:09) \n[GCC 6.4.0]"

I made sure that my default python is python3.8.

**Comment by liampaull** [comment]
@oooolga what do you see when you run: `which dts` ?

**Comment by oooolga** [comment]
`which dts` 's output is:

> /Users/olgaluo/.local/bin/dts

The packages are installed at the following directories:

> /Users/olgaluo/.local/bin/dts
> /Users/olgaluo/.local/lib/python3.7/site-packages/dt_shell/*
> /Users/olgaluo/.local/lib/python3.7/site-packages/duckietown_shell-5.1.10.dist-info/*

**Comment by liampaull** [comment]
I can't seem to reproduce this. Maybe @CourchesneA or @afdaniele  has some idea?

**Comment by CourchesneA** [comment]
I'm not familiar with how we decide which version of `dts` gets installed, but it looks like this is what would happen if you were to install using `pip` for python2.7. I would recommend uninstalling through pip3 (+ removing ~/.dt-shell to make sure) and reinstall using `python3 -m pip install --no-cache-dir --user -U duckietown-shell`

additionally, please look for anything unusual in your system:
`pip3 --version`
`ls -l /usr/bin/python3`
anything you might have done using `update-alternatives`

**Comment by oooolga** [comment]
Thanks @liampaull !

 @CourchesneA I installed duckietown-sheel using the `python3 -m pip install --no-cache-dir --user -U duckietown-shell` command and I had the same problem.

My `pip3 --version`'s output is 

> pip 20.2.3 from /Users/olgaluo/anaconda3/lib/python3.7/site-packages/pip (python 3.7)

and my python is up to date as well.

I am not very familiar with Docker. Could this be a problem caused by my default python library linked to docker? If so, how should I fix this?

P.S. I am using macOS system.

**Comment by Velythyl** [comment]
Out of curiosity/as a sanity check, can you post the output of `pip3 list` and verify that duckietown-shell is in it (and its version), just in case pip is at fault somehow?

**Comment by oooolga** [comment]
The following lines are the output of `pip3 list | grep duckie`:

> duckietown-challenges-daffy        5.1.5
> duckietown-shell                   5.1.10

**Comment by CourchesneA** [comment]
Do you have pip for python2 installed ? (`python2.7 -m pip list`)
Can you try reinstalling with `pip3 install -U -I --no-cache-dir duckietown-shell`

**Comment by oooolga** [comment]
Solved. Thanks!
