### ISSUE TITLE
dts init_sd_card generates a wrong calibration file [watchtower]

### ISSUE THREAD

**Issue by jasonhu5** [duckietown/duckietown-shell-commands#213]
When `dts --set-version daffy init_sd_card --hostname watchtower118 --country CH --type watchtower`, the successfully flashed SD card generates a camera intrinsic calibration file, with the correct name, watchtower118.yaml, but the content is wrong. Please see attached screenshot: (left is the saved original calibration, right is the generated calib file)

![image](https://user-images.githubusercontent.com/10885835/93472220-aa3c2b00-f8f4-11ea-8b38-985d9c96e3b7.png)

**Comment by afdaniele** [comment]
This makes no sense!

**Comment by jasonhu5** [comment]
I know. I was suspecting that the offset was somehow messed up. Yesterday this was the case for 2 sd-cards flashed on 2 machines.

Don't worry anymore. Closing this issue because we are not able to reproduce the problem today with another 2 trials.
