### ISSUE TITLE
dts duckiebot update default confirmation error

### ISSUE THREAD

**Issue by lifetheater57** [duckietown/duckietown-shell-commands#227]
After executing `dts duckiebot update ![robot_name]`, it asks me to confirm the application of the available updates. If I press enter, rather than explicitly type `n` or `y` and then press enter, There is an error. Since there is `[y]` following the choice description, I guess that the default action should be `y` rather than halting due to an error.

**Comment by CourchesneA** [comment]
I had a quick look at the code for this, it looks like this should already be the behavior ? would have to spend a bit more time to figure what is happening
