### ISSUE TITLE
Increase swap space on Pi during first boot

### ISSUE THREAD

**Issue by liampaull** [duckietown/duckietown-shell-commands#25]
the commands that I run are:

    $ sudo apt update
    $ sudo apt install -y dphys-swapfile
    $ sudo nano /etc/dphys-swapfile
add 
`CONF_SWAPSIZE=2048`
     $ sudo /etc/init.d/dphys-swapfile restart

We need this done on first boot. How to do it?

**Comment by liampaull** [comment]
@breandan @AndreaCensi can one of tell me at least what file is getting run on first boot and I can make the mods

**Comment by AndreaCensi** [comment]
@liampaull https://github.com/duckietown/duckietown-shell-commands/blob/9a623fb2f3a33829fcf7bea6aed68db3575424a8/init_sd_card.scripts/init_sd_card.sh#L259

**Comment by AndreaCensi** [comment]
@breandan btw I think we should remove the `rpi-health` container unless it can fit the 2 GB limit


Also it would really help everybody if we could have 16 GB so that we can pre-load all the demos. Any way to do that?

**Comment by liampaull** [comment]
thumbs up on the previous but the discussion belongs somewhere else - I will update the init script and test

**Comment by AndreaCensi** [comment]
@liampaull can you give me the complete contents of /etc/dphys-swapfile?

**Comment by AndreaCensi** [comment]
I cannot run this on first boot because "apt-get" assumes the internet is up.

**Comment by AndreaCensi** [comment]
in branch I created the file, but cannot install the package

**Comment by liampaull** [comment]
OK @AndreaCensi  here's the instructions to add for 1GB of swap, which seems to work:
```sudo dd if=/dev/zero of=/swap0 bs=1M count=1024
sudo mkswap /swap0
sudo echo "/swap0 swap swap" >> /etc/fstab
sudo chmod 0600 /swap0
sudo swapon -a
```
I have tested and can see the swap space with `free -h` and can run the lane following demo.
Can you add to SD card init script?

**Comment by liampaull** [comment]
fyi - once the lane following demo stabilizes and is running it is using about 630M of RAM

**Comment by liampaull** [comment]
@AndreaCensi is this included in the new init script for the sd card ?
