### ISSUE TITLE
dts challenges info throwing error

### ISSUE THREAD

**Issue by thealokkr** [duckietown/duckietown-shell-commands#251]
Debug Info

commands-version: daffy
dt-authentication-daffy: 0.1.5
dt-data-api-daffy: 0.1.10
duckietown-docker-utils-daffy: 6.0.77
duckietown-shell: 5.2.3
duckietown-shell-commands: 5.1.10
encodings:
  locale: UTF-8
  stderr: UTF-8
  stdout: UTF-8
python: "3.7.7 (default, May  6 2020, 04:59:01) \n[Clang 4.0.1 (tags/RELEASE_401/final)]"

Error
INFO:dts:Commands version: daffy
INFO:dts:looking at /Users/alokumar0/.dt-shell/commands-multi/daffy
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.0.77 path /Users/alokumar0/.local/lib/python3.7/site-packages
fatal: not a git repository (or any of the parent directories): .git
DEBUG:duckietown_docker_utils:/Users/alokumar0/.gitconfig -> /var/folders/hh/6w839l5j475b5jbjcdf9wzbw20vj0d/T/tmph6nlc7fo/fake-home/.gitconfig
DEBUG:duckietown_docker_utils:/Users/alokumar0/.pypirc -> /var/folders/hh/6w839l5j475b5jbjcdf9wzbw20vj0d/T/tmph6nlc7fo/fake-home/.pypirc
DEBUG:duckietown_docker_utils:/Users/alokumar0/.dt-shell -> /var/folders/hh/6w839l5j475b5jbjcdf9wzbw20vj0d/T/tmph6nlc7fo/fake-home/.dt-shell
DEBUG:duckietown_docker_utils:Need to pull docker.io/duckietown/duckietown-challenges-cli:daffy-amd64 because passed 619 > 600 seconds.
INFO:duckietown_docker_utils:'docker.io/duckietown/duckietown-challenges-cli:daffy-amd64'
name 'docker.io/duckietown/duckietown-challenges-cli'
tag 'daffy-amd64'
sha None
pull duckietown-challenges-cli:daffy-amd64 100% |##############################| ETA:  0:00:00
dts :  Traceback (most recent call last):
    :    File "/Users/alokumar0/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    :      six.raise_from(e, None)
    :    File "<string>", line 3, in raise_from
    :    File "/Users/alokumar0/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    :      httplib_response = conn.getresponse()
    :    File "/anaconda3/envs/hanu/lib/python3.7/http/client.py", line 1344, in getresponse
    :      response.begin()
    :    File "/anaconda3/envs/hanu/lib/python3.7/http/client.py", line 306, in begin
    :      version, status, reason = self._read_status()
    :    File "/anaconda3/envs/hanu/lib/python3.7/http/client.py", line 267, in _read_status
    :      line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
    :    File "/anaconda3/envs/hanu/lib/python3.7/socket.py", line 589, in readinto
    :      return self._sock.recv_into(b)
    :  socket.timeout: timed out
    :  
    :  During handling of the above exception, another exception occurred:
    :  
    :  Traceback (most recent call last):
    :    File "/Users/alokumar0/.local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    :      timeout=timeout
    :    File "/Users/alokumar0/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    :      method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
    :    File "/Users/alokumar0/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 532, in increment
    :      raise six.reraise(type(error), error, _stacktrace)
    :    File "/Users/alokumar0/.local/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    :      raise value
    :    File "/Users/alokumar0/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    :      chunked=chunked,
    :    File "/Users/alokumar0/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    :      self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
    :    File "/Users/alokumar0/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 337, in _raise_timeout
    :      self, url, "Read timed out. (read timeout=%s)" % timeout_value
    :  urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
    :  
    :  During handling of the above exception, another exception occurred:
    :  
    :  Traceback (most recent call last):
    :    File "/anaconda3/envs/hanu/lib/python3.7/site-packages/dt_shell/main.py", line 38, in cli_main
    :      cli_main_()
    :    File "/anaconda3/envs/hanu/lib/python3.7/site-packages/dt_shell/main.py", line 194, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/anaconda3/envs/hanu/lib/python3.7/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/anaconda3/envs/hanu/lib/python3.7/site-packages/dt_shell/cli.py", line 278, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/anaconda3/envs/hanu/lib/python3.7/site-packages/dt_shell/dt_command_abs.py", line 48, in do_command
    :      cls.command(shell, args)
    :    File "/Users/alokumar0/.dt-shell/commands-multi/daffy/challenges/command.py", line 83, in command
    :      docker_credentials=docker_credentials,
    :    File "/Users/alokumar0/.local/lib/python3.7/site-packages/duckietown_docker_utils/docker_run.py", line 274, in generic_docker_run
    :      container = client.containers.run(image, **params)
    :    File "/Users/alokumar0/.local/lib/python3.7/site-packages/docker/models/containers.py", line 818, in run
    :      container.start()
    :    File "/Users/alokumar0/.local/lib/python3.7/site-packages/docker/models/containers.py", line 404, in start
    :      return self.client.api.start(self.id, **kwargs)
    :    File "/Users/alokumar0/.local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    :      return f(self, resource_id, *args, **kwargs)
    :    File "/Users/alokumar0/.local/lib/python3.7/site-packages/docker/api/container.py", line 1110, in start
    :      res = self._post(url)
    :    File "/Users/alokumar0/.local/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
    :      return f(self, *args, **kwargs)
    :    File "/Users/alokumar0/.local/lib/python3.7/site-packages/docker/api/client.py", line 233, in _post
    :      return self.post(url, **self._set_request_timeout(kwargs))
    :    File "/Users/alokumar0/.local/lib/python3.7/site-packages/requests/sessions.py", line 590, in post
    :      return self.request('POST', url, data=data, json=json, **kwargs)
    :    File "/Users/alokumar0/.local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    :      resp = self.send(prep, **send_kwargs)
    :    File "/Users/alokumar0/.local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    :      r = adapter.send(request, **kwargs)
    :    File "/Users/alokumar0/.local/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    :      raise ReadTimeout(e, request=request)
    :  requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

**Comment by liampaull** [comment]
what is your configuration/OS etc?

**Comment by thealokkr** [comment]
MacOS Mojave.
Conda Python 3.7 and I used https://pypi.org/project/duckietown-shell/ to install the shell

**Comment by jasonhu5** [comment]
If this is still a problem, please reopen the issue
