### ISSUE TITLE
dts --set-version daffy

### ISSUE THREAD

**Issue by 2-bit-creat** [duckietown/duckietown-shell-commands#254]
dts : Problems with a command?
:
: Report here: https://github.com/duckietown/duckietown-shell-commands/issues
:
: Troubleshooting:
:
: - If some commands update fail, delete ~/.dt-shell/commands
:
: - To reset the shell to "factory settings", delete ~/.dt-shell
:
: (Note: you will have to re-configure.)

I don't know what I did wrong..

**Comment by afdaniele** [comment]
Nothing wrong, that is a question, not a statement. There are no problems.

**Comment by 2-bit-creat** [comment]
My email adress is ***@***.***

I wrote the above email in Slack, but I didn't received any email. So I used this email instead. Please add me with ***@***.***) this email.

Best,
Seyeong
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by edf42001** [comment]
Oh, so the command works successfully but just has this as output? That's slightly confusing.
