### ISSUE TITLE
dts challenges info failing.

### ISSUE THREAD

**Issue by JoostSP** [duckietown/duckietown-shell-commands#259]
Hi all,

I'm trying the follow the instructions from The AI Driving Olympics, unit C2 - Software requirements (for the Duckietown edX course). All works until I type in: `dts challenges info` which gives quite a long error list (attatched as logfile). I'm running on a Ubuntu 20.04 LTS desktop.

Anyone an idea for me?

Thanks,
Joost
[shell-debug-info.txt](https://github.com/duckietown/duckietown-shell-commands/files/6217790/shell-debug-info.txt)
[challenges_2021_03_28_19_52_58_761910_10.txt](https://github.com/duckietown/duckietown-shell-commands/files/6217792/challenges_2021_03_28_19_52_58_761910_10.txt)

**Comment by AndreaCensi** [comment]
Seems like it was an invalid token. Please do "dts tok set" and retry.

**Comment by JoostSP** [comment]
Dear Andrea,
*blush* I only copied the directly visible part of my DuckieTown token.
It works now!
Sorry for this beginner mistake!
Joost
