### ISSUE TITLE
dts --set-version daffy issue

### ISSUE THREAD

**Issue by jagadishvaka** [duckietown/duckietown-shell-commands#261]
I am getting the below error while keying in the 'dts --set-version daffy
' command.

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)

**Comment by reachpranjal** [comment]
Same Issue.
Using Ubuntu 18.04

**Comment by rikardofernand** [comment]
me too.

**Comment by a-al-s** [comment]
I got the same error
anyone knows how to fix it?

**Comment by jasonhu5** [comment]
From line `dts: Problem with ...` to `: (Note: ...` seem to be normal prompt messages. Are there any other/further error messages?

**Comment by jasonhu5** [comment]
It seems this confusion is resolved.
