### ISSUE TITLE
command dts not found 

### ISSUE THREAD

**Issue by engmahzoob** [duckietown/duckietown-shell-commands#264]
when i run which dts i dont get any response, if i need to fix a path shell initialization path , how would i do that , where can i locate the file . if i run dts version 
i get "command not found ",did you mean
command ots
command dte
and so on 
can any one please guide me  how to fix this error. i am a beginner.so if you are kindly suggesting to change path or delete or uninstall ,please do tell me how do that

**Comment by afdaniele** [comment]
This was solved here: https://stackoverflow.com/c/duckietown/questions/269

**Comment by engmahzoob** [comment]
thanks for the prompt response afdaniele
