### ISSUE TITLE
dts exercises lab

### ISSUE THREAD

**Issue by 2-bit-creat** [duckietown/duckietown-shell-commands#270]
seyeong@seyeong-930QAA:~$ dts exercises lab

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)
INFO:dts:Commands version: daffy

There is an updated duckietown-shell available.

  You have: 5.2.3

  Available: 5.2.7 
 
WARNING: We strongly recommend updating to the latest version. ONLY THE LATEST VERSION IS SUPPORTED!
         If you experience issues, please make sure you're using the latest version before posting questions or issues. 

You can update the shell using `pip`.        
        
        
INFO:dts:looking at /home/seyeong/.dt-shell/commands-multi/daffy
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.0.77 path /home/seyeong/.local/lib/python3.8/site-packages
INFO:dts:Exercise name: seyeong

dts :  You must run this command inside an exercise directory containing a `config.yaml` file.

dts :  To report a bug, please also include the contents of /tmp/shell-debug-info.txt

(I cannot find the web link here. I thought the problem was my update status of duckietown-shell. So, I tried to update duckietown-shell by using pip. But it says)

seyeong@seyeong-930QAA:~$ pip install duckietown-shell --upgrade

Command 'pip' not found, but there are 18 similar ones.

**Comment by tanij** [comment]
Run this instead:  `pip3 install --no-cache-dir --user -U duckietown-shell`

Details in the readme here: https://github.com/duckietown/duckietown-shell

**Comment by 2-bit-creat** [comment]
Thank you! but it still doesn't work. I'm just running the command on my linux terminal. I don't know how I can do this. "You must run this command inside an exercise directory containing a `config.yaml` file."

seyeong@seyeong-930QAA:~$ dts exercises lab

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)
INFO:dts:Commands version: daffy
INFO:dts:looking at /home/seyeong/.dt-shell/commands-multi/daffy
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.0.82 path /home/seyeong/.local/lib/python3.8/site-packages
INFO:dts:Exercise name: seyeong

dts :  You must run this command inside an exercise directory containing a `config.yaml` file.

dts :  To report a bug, please also include the contents of /home/seyeong/shell-debug-info.txt

**Comment by liampaull** [comment]
you need to run that command from inside an exercise folder.

**Comment by 2-bit-creat** [comment]
> you need to run that command from inside an exercise folder.

Thank you for the reply. 
I'm not familiar with Ubuntu linux. How can I run the command inside the folder? I don't know how I can access the folder. Is the folder downloaded on my desktop?

**Comment by xristoskor** [comment]
> > you need to run that command from inside an exercise folder.
> 
> Thank you for the reply.
> I'm not familiar with Ubuntu linux. How can I run the command inside the folder? I don't know how I can access the folder. Is the folder downloaded on my desktop?

@2-bit-creat  
I have the same issue with you and I'm not familiar too. Did you find a solution? I don't know how to run a command inside an exercise directory.

**Comment by Muralimanohar123** [comment]
Dear all,

How to log into 'dts exercises lab'...Where is this folder available

**Comment by maykonpacheco** [comment]
@2-bit-creat @Muralimanohar123 
https://docs.duckietown.org/daffy/duckietown-robotics-development/out/python_programs_environments.html
