### ISSUE TITLE
config.yaml

### ISSUE THREAD

**Issue by 2-bit-creat** [duckietown/duckietown-shell-commands#273]
I want to run this command (dts exercises lab). In order to do that, I need to access config.yaml file. How can I access this file from my terminal?? Also, is it fine to finish this homework before 30th June to get a certificate?

**Comment by rampallishyam** [comment]
I had the same issue. Thanks for posting. Let us wait for any reply.

**Comment by rampallishyam** [comment]
I have figured out the issue. Please clone the "mooc-exercises" repository and follow the instructions in the README.

**Comment by jasonhu5** [comment]
> I need to access config.yaml file. How can I access this file from my terminal?

As mentioned by @rampallishyam, first clone the `duckietown/mooc-exercises` repository. For each exercise, enter the relevant exercise folder with `cd [FOLDER_PATH]`. And in the exercise folder, the respective `config.yaml` file should be present and please follow the README document.

> Also, is it fine to finish this homework before 30th June to get a certificate?

Please ask the MOOC administrative questions on the platform forums.

Feel free to reopen if same technical problems remain.
