### ISSUE TITLE
dts desktop update stalls at 74% for more that 45 minutes... I am struggling for last couple of days.. Has anyone else faced the same issue.. Any clues welcome

### ISSUE THREAD

**Issue by haridaspt** [duckietown/duckietown-shell-commands#287]
dts desktop update stalls at 74% for more that 45 minutes... I am struggling for last couple of days.. Has anyone else faced the same issue.. Any clues welcome

ubuntu@ubuntu-VB:~$ dts desktop update

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)
INFO:dts:Commands version: daffy
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.0.82 path /home/ubuntu/.local/lib/python3.8/site-packages
INFO:dts:Pulling image `duckietown/dt-gui-tools:daffy-amd64`...
Done!
INFO:dts:Pulling image `duckietown/dt-core:daffy-amd64`...
Done!
INFO:dts:Pulling image `duckietown/dt-duckiebot-fifos-bridge:daffy-amd64`...
Done!
INFO:dts:Pulling image `duckietown/challenge-aido_lf-baseline-duckietown:daffy-amd64`...
Done!
INFO:dts:Pulling image `duckietown/challenge-aido_lf-baseline-duckietown-ml:daffy-amd64`...
Progress: [===========================================================================>                        ] 74%

**Comment by tanij** [comment]
I experienced this too, although it was more like 10 minutes rather than 45. It did continue working in my case, just by waiting.

**Comment by tanij** [comment]
Confirmed: 45mins sounds extreme but it's the first time it is downloading the ML image, which is quite large. Unless it spits out an error, just leaving it on is the way to go.

**Comment by haridaspt** [comment]
Thank you.. I had to leave it on.. yesterday night today morning it got completed.. without any errors. It seems even if there is no update available it does do something every time you issue 'dts desktop update' command.. and stops at 68% and then for a much longer period at 74%. [Was a little foolish to try dts desktop update once more today :( ]. Hope I can abort it now.. and try the exercises

**Comment by haridaspt** [comment]
ubuntu@ubuntu-VB: \~/.local$ cat /usr/bin/whatchanged.sh
find . -type f -printf '%T@ %Td-%Tb-%TY %TH:%TM:%TS %p\n' |sort -n | tail -10 | cut -f2- -d" "
ubuntu@ubuntu-VB:\~/.local$ whatchanged.sh 
02-Jun-2021 09:33:06.8885730010 ./share/xorg/Xorg.0.log.old
02-Jun-2021 09:40:18.6024526660 ./share/gvfs-metadata/home
02-Jun-2021 09:40:18.6064526830 ./share/gvfs-metadata/home-673e92d6.log
02-Jun-2021 10:47:10.5092885350 ./share/evolution/addressbook/system/contacts.db
02-Jun-2021 10:54:57.4768771330 ./share/tracker/data/tracker-store.journal
02-Jun-2021 11:58:30.1582816280 ./share/gvfs-metadata/root
02-Jun-2021 11:58:30.1822818790 ./share/gvfs-metadata/root-0d8c27a2.log
02-Jun-2021 12:08:15.5352865280 ./share/xorg/Xorg.0.log
02-Jun-2021 12:10:42.2003165010 ./share/recently-used.xbel
02-Jun-2021 12:18:23.1032898510 ./share/gnome-shell/application_state
ubuntu@ubuntu-VB:~/.local$ 
Nothing much seems to be being written atleast in the home .local folder

**Comment by haridaspt** [comment]
Unfortunately while trying to 'dts exercises build' I got the following error... 
ubuntu@ubuntu-VB:~/mooc-exercises/modcon$ dts exercises build

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)
INFO:dts:Commands version: daffy
INFO:dts:looking at /home/ubuntu/.dt-shell/commands-multi/daffy
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.0.82 path /home/ubuntu/.local/lib/python3.8/site-packages
INFO:dts:Exercise name: modcon
INFO:dts:Building environment...
Step 1/8 : FROM duckietown/dt-gui-tools:daffy-amd64
 ---> b8ecebb758e0
Step 2/8 : RUN pip3 install -U     aido-protocols-daffy
 ---> Using cache
 ---> 089773fc5fce
Step 3/8 : COPY assets/vnc/image/root/Desktop/. /root/Desktop/
 ---> Using cache
 ---> ebbcbd7c2614
Step 4/8 : COPY assets/vnc/image/root/Documents/. /root/Documents/
 ---> Using cache
 ---> b5130e586c12
Step 5/8 : COPY assets/vnc/image/root/icons/. /root/.icons/
 ---> Using cache
 ---> 2d9efa5a1e26
Step 6/8 : COPY assets/vnc/image/usr/bin/. /usr/bin/
 ---> Using cache
 ---> 15d083da8ee4
Step 7/8 : COPY assets/vnc/image/opt/ros/noetic/share/rviz/. /opt/ros/noetic/share/rviz/
 ---> Using cache
 ---> 5540a5b6faa4
Step 8/8 : CMD ["dt-launcher-jupyter"]
 ---> Using cache
 ---> 1299f02203c4
Successfully built 1299f02203c4
Successfully tagged ubuntu/exercise-modcon-lab:latest
INFO:dts:Environment built!
INFO:dts:Converting the solution/04-Odometry/odometry_activity.ipynb into a Python script...
INFO:dts:Temp filtered file : /tmp/odometry_activity.ipynb
INFO:dts:Deleting temp file : /tmp/odometry_activity.ipynb
INFO:dts:Converting the solution/05-PID-Control/PID_controller.ipynb into a Python script...
INFO:dts:Temp filtered file : /tmp/PID_controller.ipynb
INFO:dts:Deleting temp file : /tmp/PID_controller.ipynb
INFO:dts:Converting the solution/06-PID-Control-Homework/PID_controller_homework.ipynb into a Python script...
INFO:dts:Temp filtered file : /tmp/PID_controller_homework.ipynb
INFO:dts:Deleting temp file : /tmp/PID_controller_homework.ipynb
Forcing ROS_MASTER_URI=http://localhost:11311
<== Entrypoint
Traceback (most recent call last):
  File "/usr/bin/catkin", line 11, in <module>
    load_entry_point('catkin-tools==0.5.0', 'console_scripts', 'catkin')()
  File "/usr/lib/python3/dist-packages/catkin_tools/commands/catkin.py", line 272, in main
    catkin_main(sysargs)
  File "/usr/lib/python3/dist-packages/catkin_tools/commands/catkin.py", line 267, in catkin_main
    sys.exit(args.main(args) or 0)
  File "/usr/lib/python3/dist-packages/catkin_tools/verbs/catkin_build/cli.py", line 363, in main
    mark_space_as_built_by(ctx.build_space_abs, 'catkin build')
  File "/usr/lib/python3/dist-packages/catkin_pkg/tool_detection.py", line 78, in mark_space_as_built_by
    with open(marker_path, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/code/solution/build/.built_by'

dts :  Traceback (most recent call last):
    :    File "/home/ubuntu/.local/lib/python3.8/site-packages/dt_shell/main.py", line 38, in cli_main
    :      cli_main_()
    :    File "/home/ubuntu/.local/lib/python3.8/site-packages/dt_shell/main.py", line 195, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/ubuntu/.local/lib/python3.8/site-packages/dt_shell/cli.py", line 278, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/ubuntu/.local/lib/python3.8/site-packages/dt_shell/dt_command_abs.py", line 41, in do_command
    :      cls.commands[word].do_command(cls.commands[word], shell, " ".join(parts[1:]))
    :    File "/home/ubuntu/.local/lib/python3.8/site-packages/dt_shell/dt_command_abs.py", line 54, in do_command
    :      cls.command(shell, args)
    :    File "/home/ubuntu/.dt-shell/commands-multi/daffy/exercises/build/command.py", line 222, in command
    :      start_command_in_subprocess(attach_cmd)
    :    File "/home/ubuntu/.dt-shell/commands-multi/daffy/utils/cli_utils.py", line 51, in start_command_in_subprocess
    :      raise Exception(msg)
    :  Exception: Error occurred while running "docker attach ros_template_catkin_build", please check and retry (1)

dts :  To report a bug, please also include the contents of /home/ubuntu/shell-debug-info.txt


The contents of the shell-debug-info.txt is

ubuntu@ubuntu-VB:~/mooc-exercises/modcon$ cat /home/ubuntu/shell-debug-info.txt
commands-version: daffy
dt-authentication-daffy: 0.1.5
dt-data-api-daffy: 0.1.10
duckietown-docker-utils-daffy: 6.0.82
duckietown-shell: 5.2.8
duckietown-shell-commands: 5.3.20210414
encodings:
  locale: UTF-8
  stderr: utf-8
  stdout: utf-8
python: "3.8.5 (default, Jan 27 2021, 15:41:15) \n[GCC 9.3.0]"

**Comment by haridaspt** [comment]
Should i start all from beginning.. as mentioned in https://github.com/duckietown/duckietown-shell/blob/daffy/README.md

**Comment by jasonhu5** [comment]
I think the later problem has been solved. Closing now
