### ISSUE TITLE
dts excercises lab : config.yaml

### ISSUE THREAD

**Issue by Jeeva-Dj** [duckietown/duckietown-shell-commands#293]
How to solve the below :

dts exercises lab

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)
INFO:dts:Commands version: daffy
INFO:dts:looking at /home/dj/.dt-shell/commands-multi/daffy

dts :  An updated version of the commands is available.
    :  
    :  Attempting auto-update.

dts :  Updating commands...

dts :  OK
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.0.82 path /home/dj/.local/lib/python3.8/site-packages
INFO:dts:Exercise name: dj

dts :  You must run this command inside an exercise directory containing a `config.yaml` file.

dts :  To report a bug, please also include the contents of /home/dj/shell-debug-info.txt

**Comment by jasonhu5** [comment]
It looks like the command was not initiated from an exercise folder. Please make sure `dts exercises lab` is used in a specific exercise folder, where there is a config.yaml file.
