### ISSUE TITLE
Need to pass at least one command among the following -- can't procced ; stuck at initial stage

### ISSUE THREAD

**Issue by hengjoontiang** [duckietown/duckietown-shell-commands#294]
hengjt@hengjt-Lenovo-ideapad-500-15ISK:~$ dts challenges

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)
INFO:dts:Commands version: daffy
INFO:dts:looking at /home/hengjt/.dt-shell/commands-multi/daffy
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.0.82 path /home/hengjt/.local/lib/python3.8/site-packages
fatal: not a git repository (or any of the parent directories): .git
DEBUG:duckietown_docker_utils:/home/hengjt/.gitconfig -> /tmp/tmpfrzgszza/fake-home/.gitconfig
DEBUG:duckietown_docker_utils:/home/hengjt/.dt-shell -> /tmp/tmpfrzgszza/fake-home/.dt-shell
DEBUG:duckietown_docker_utils:Need to pull docker.io/duckietown/duckietown-challenges-cli:daffy-amd64 because passed 3181 > 600 seconds.
INFO:duckietown_docker_utils:'docker.io/duckietown/duckietown-challenges-cli:daffy-amd64'
name 'docker.io/duckietown/duckietown-challenges-cli'
tag 'daffy-amd64'
sha None
DEBUG:commons:version: 6.1.7 *:daffy-amd64 100% |################| ETA:  0:00:00
INFO:typing:version: 6.1.8
DEBUG:duckietown_challenges_cli:duckietown_challenges_cli version 6.0.92 path /usr/local/lib/python3.8/dist-packages
DEBUG:duckietown_challenges:duckietown_challenges version 6.3.4 path /usr/local/lib/python3.8/dist-packages
DEBUG:ipce:version 6.0.36 path /usr/local/lib/python3.8/dist-packages
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.0.82 path /usr/local/lib/python3.8/dist-packages
DEBUG:duckietown_build_utils:duckietown_build_utils version 6.2.3 path /usr/local/lib/python3.8/dist-packages
DEBUG:duckietown_challenges_runner:duckietown_challenges_runner version 6.2.20 path /usr/local/lib/python3.8/dist-packages
06:01:05|d|duckietown_challenges_cli|cli.py:171|dt_challenges_cli_main_():
Need to pass at least one command among the following.

# User commands

User commands

         info  Information about your account.
     evaluate  Evaluates a submission locally.
       submit  Make a submission
       follow  Follows the fate of a submission.
       retire  Retires a submission.
         list  Lists submissions on the server.
        reset  Resets a submission (forces re-doing of jobs)
    evaluator  Runs an evaluator.
     download  Lists submissions on the server.

# Admin commands

Admin commands

      auth  [admin only] Queries the authorization profiles.
    define  [admin only] Defines a challenge.

dts :  Execution of docker image failed. Return code: 2.
    :  
    :  The log is available at /tmp/hengjt/duckietown/dt-shell-commands/challenges/challenges_2021_07_05_14_00_55_660610_2.txt

dts :  To report a bug, please also include the contents of /home/hengjt/shell-debug-info.txt
hengjt@hengjt-Lenovo-ideapad-500-15ISK:~$ cat /home/hengjt/shell-debug-info.txt
commands-version: daffy
dt-authentication-daffy: 0.1.5
dt-data-api-daffy: 0.1.10
duckietown-docker-utils-daffy: 6.0.82
duckietown-shell: 5.2.8
duckietown-shell-commands: 5.3.20210414
encodings:
  locale: UTF-8
  stderr: utf-8
  stdout: utf-8
python: "3.8.10 (default, Jun  2 2021, 10:49:15) \n[GCC 9.4.0]"

**Comment by jasonhu5** [comment]
What documentation are you following? It seems `dts challenges` needs extra specific commands, e.g. `info` for showing user id and stuff, `submit` for submitting to the server

**Comment by jasonhu5** [comment]
Closing for now unless it remains problematic
