### ISSUE TITLE
Shutdown and reboot commands fail

### ISSUE THREAD

**Issue by Guitaricet** [duckietown/duckietown-shell-commands#303]
Hi!

Commands `dts duckiebot shutdown vlialin` and `dts duckiebot reboot vliali` both fail with the same error message.

```bash
INFO:dts:Commands version: daffy
INFO:dts:looking at /home/vlialin/.dt-shell/commands-multi/daffy
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.0.82 path /home/vlialin/.local/lib/python3.8/site-packages
INFO:dts:Shutting down vlialin...
ERROR:dts:Expecting value: line 1 column 1 (char 0)
```

Error message is not very descriptive and `dts duckiebot shutdown --help` does not show any extra arguments. Any ideas what the problem might be?

Environment:
* Ubuntu 20.04.3 LTS
* Python 3.9.5
* dts version 5.2.8
* Duckiebot DB19

**Comment by sourav-paul** [comment]
@Guitaricet What's the overall status on your dashboard?

**Comment by BenoitAud** [comment]
Anyone has found the solution to this issue? I have the same, I can reboot but not shutdown with these commands.

**Comment by jasonhu5** [comment]
If the issue persists with latest `dts` and commands (`5.4.5`), please feel free to reopen the issue.

**Comment by THE0ARYANDUGGAL0experience** [comment]
I was facing this issue also but I solved it simply by taking out the power cable from the circuit board. I would suggest that you use this method for emergencies only because it may lead to your software getting corrupted.
