### ISSUE TITLE
Burning SD card

### ISSUE THREAD

**Issue by thanksforhelpingme** [duckietown/duckietown-shell-commands#316]
I am not sure what is happening. I flashed the SD card and it failed multiple times, saying input/output error. What happens is the small sd reader that was provided with the DB19 duckiebot model will just randomly disconnect from my laptop. I can leave it in for hours but once I start flashing onto it, it will disconnect randomly. I have tried all the usb ports on my laptop and the farthest I have gotten to was fully flashed and 76% verified. It disconnected and I just about cried because it takes about an hour to flash and so far it looks like the same amount of time to verify. Does anyone have any sort of idea why this is happening?

**Comment by afdaniele** [comment]
Do you have a different SD card reader or perhaps one embedded inside your laptop that you can test?

**Comment by thanksforhelpingme** [comment]
Yes, I will use a different SD card soon. I do not currently have internet at my house. I have an SD card slot on my laptop but it looks like I need some sort of adapter for the smaller SD card. I will try these when my internet is back up and I will let you know if it works.

**Comment by thanksforhelpingme** [comment]
I ended up trying again and again and it eventually worked, not sure exactly what I changed. Just happened to finish all the way through, thanks for the help.
