### ISSUE TITLE
Burning SD card - KeyError: 'Content-Length'

### ISSUE THREAD

**Issue by fahad-said** [duckietown/duckietown-shell-commands#318]
I was trying to flash my first duckiebot(according to the manual), but came across an error right after i tries to download "dt-nvidia-jetpack-v1.2.2-2gb.zip" as shown below: 

![Screenshot from 2021-12-17 11-00-01](https://user-images.githubusercontent.com/96290024/146527816-3d8a6e70-7277-46ad-bb7d-4790b86fe083.png)

I reinstalled ubuntu 20.04 lts, docker and duckieshell. Even reinstalled docker-compose. Any suggestions to what it could be? Should I try to install another version of linux ? I'm kinda new to this operating system and duckietown. 

Debugging info:
[shell-debug-info.txt](https://github.com/duckietown/duckietown-shell-commands/files/7734265/shell-debug-info.txt)

**Comment by kochaika** [comment]
The same problem (with `disk_image/dt-hypriotos-rpi-v1.2.1.zip`)

**Comment by tanij** [comment]
This was related to a problem in the Duckietown AWS backend. It should be solved now.
