### ISSUE TITLE
Failed to run the gym simulator

### ISSUE THREAD

**Issue by Edi-M** [duckietown/duckietown-shell-commands#321]
Hi,
dts exercises test --sim fails as follows:

dts exercises test --sim

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)
INFO:dts:Commands version: daffy-montreal21
INFO:dts:looking at /home/d001/.dt-shell/commands-multi/daffy-montreal21
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.0.97 path /home/d001/.local/lib/python3.8/site-packages
INFO:dts:Log levels = agent:debug manager:none simulator:none bridge:none vnc:none
INFO:dts:Running exercise braitenberg
INFO:dts:Note: Running locally since we are using simulator
INFO:dts:https://challenges.duckietown.org/v4/api/challenges/mooc-BV1/description
INFO:dts:Removing container ex-braitenberg-challenge-aido_lf-simulator-gym
INFO:dts:Removing container ex-braitenberg-experiment-manager
INFO:dts:Results will be stored in: /tmp/d001/exercises-test/94165/run-challenges
INFO:dts:Running simulator ex-braitenberg-challenge-aido_lf-simulator-gym from docker.io/andreacensi/duckietown-challenges@sha256:f6e97655c6dbe5966e76cbba2afb40fb8b138b1c95181b8e862852ae64b20356
INFO:dts:Running experiment_manager ex-braitenberg-experiment-manager from docker.io/andreacensi/duckietown-challenges@sha256:96e899b76f9e102b9cabc69f0bfef166bf63a19f9906d6f135b55a7c4c8fa9ba
INFO:dts:
	Sim interface will be running at http://localhost:8090/

INFO:dts:Starting monitor thread
INFO:dts:Containers to monitor: ['ex-braitenberg-experiment-manager', 'ex-braitenberg-challenge-aido_lf-simulator-gym']
INFO:dts:Starting attached container
INFO:dts:Running the ex-braitenberg-agent from docker.io/duckietown/challenge-aido_lf-template-random:daffy-amd64
DEBUG:typing:version: 6.2.3
DEBUG:nodes:version 6.2.13 path /usr/local/lib/python3.8/dist-packages pyparsing 2.4.6
DEBUG:ipce:version 6.1.1 path /usr/local/lib/python3.8/dist-packages
usage: node-launch [-h] --config CONFIG [--protocol PROTOCOL] [--node NODE] [--check]
node-launch: error: unrecognized arguments: /code/launchers/run_agent.sh
ERROR:dts:Attached container terminated Error occurred while running "docker  attach ex-braitenberg-agent", please check and retry (2)
INFO:dts:Stopping container monitor...
INFO:dts:Container monitor stopped.
INFO:dts:Cleaning containers...
INFO:dts:Stopping container ex-braitenberg-experiment-manager
INFO:dts:Stopping container ex-braitenberg-challenge-aido_lf-simulator-gym
INFO:dts:Waiting for container ex-braitenberg-experiment-manager to stop...
INFO:dts:Waiting for container ex-braitenberg-challenge-aido_lf-simulator-gym to stop...
INFO:dts:attached container already stopped.
INFO:dts:All done, your results are available in: /tmp/d001/exercises-test/94165/run-challenges

Environment:
- Ubuntu 20.04.4. LTS
- dts version 5.2.19
- Duckiebot DB21M
- Python 3.8.10
- Docker version:
Client: Docker Engine - Community
 Version:           20.10.13
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 10 14:07:51 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.13
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       906f57f
  Built:            Thu Mar 10 14:05:44 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.10
  GitCommit:        2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Thanks!

**Comment by liampaull** [comment]
can you set the version of shell to `daffy`?

**Comment by Edi-M** [comment]
Well, I changed to daffy but had the same error. I checked everything without success (the same error every time). Then I decided to start from scratch again. So I installed Ubuntu onto another computer, I carefully followed each and every step from the beginning according to mooc and duckietown requirements (laptop and accounts setup, as well as the duckiebot SD card setup). I managed to solve the mooc exercises (files braitenberg01 to 03.ipynb, changed connections.py and preprocessing.py). I tested my solution on braitenberg03.ipynb and it I think it performs OK if it is to check with the help of test figures at the end of the code from this file.

However, when I try to test in simulation, I receive the same error as before. Same situation if I want to test my solution on my duckiebot. My system is updated and upgraded to the last versions of everything (Ubuntu, Python, dts etc.), but it looks like some docker image is outdated (maybe I am wrong, because I am not skilled in Docker):
dts:Running the ex-braitenberg-agent from docker.io/duckietown/challenge-aido_lf-template-random:daffy-amd64
DEBUG:typing:version: 6.2.3
DEBUG:nodes:version 6.2.13 path /usr/local/lib/python3.8/dist-packages pyparsing 2.4.6
DEBUG:ipce:version 6.1.1 path /usr/local/lib/python3.8/dist-packages
usage: node-launch [-h] --config CONFIG [--protocol PROTOCOL] [--node NODE] [--check]
**node-launch: error: unrecognized arguments: /code/launchers/run_agent.sh**
ERROR:dts:Attached container terminated Error occurred while running "docker attach ex-braitenberg-agent", please check and retry (2)

I checked slack and discovered that I am not the only one with this error. In the end, the other guys decided to skip this step. Well, I think I will do the same after all, but it is a little bit pity it doesn't work on the robot :(
I really don't know where I am wrong because I tried not to miss any step.
