### ISSUE TITLE
start_gui_tools and ROS not working

### ISSUE THREAD

**Issue by GoldenDuckie** [duckietown/duckietown-shell-commands#343]
Hello,
I am currently working on calibrating the motors of the duckiebot and it requires you to run `dts start_gui_tools robotname` and ROS. Both of them are not working. I have tried dts desktop update, dts update, the desktop environment on the duckiebot dashboard works fine. I will attach the error at the end.

Here is the shell-debug-info.txt
`commands-version: daffy
dt-authentication-daffy: 0.1.5
dt-data-api-daffy: 1.0.1
duckietown-docker-utils-daffy: 6.0.97
duckietown-shell: 5.2.21
duckietown-shell-commands: 5.4.5
encodings:
  locale: UTF-8
  stderr: utf-8
  stdout: utf-8
python: 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]`

![image](https://user-images.githubusercontent.com/117852926/203607222-ed5dbb90-588a-4192-a36b-c9d9d9678f0f.png)

**Comment by jasonhu5** [comment]
Resolved on Slack. The cause was unclear. The problem was gone after reinstalling Ubuntu22.04
