### ISSUE TITLE
Failing to update duckiebot

### ISSUE THREAD

**Issue by ethan-allan** [duckietown/duckietown-shell-commands#345]
osboxes@osboxes:~$ dts duckiebot update psyduck

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)
INFO:dts:Commands version: daffy
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.0.97 path /home/osboxes/.local/lib/python3.8/site-packages
INFO:dts:Fetching list of containers...
INFO:dts:Removing 0 containers.
INFO:dts:Fetching list of images...
INFO:dts:Removing 0 images.
INFO:dts:Nothing to do
INFO:dts:Logging in to docker.io as '...' with secret '...'`

dts :  Traceback (most recent call last):
    :    File "/usr/lib/python3/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    :      response.raise_for_status()
    :    File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    :      raise HTTPError(http_error_msg, response=self)
    :  requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.0.182:2375/v1.35/auth
    :  
    :  During handling of the above exception, another exception occurred:
    :  
    :  Traceback (most recent call last):
    :    File "/home/osboxes/.local/lib/python3.8/site-packages/dt_shell/main.py", line 40, in cli_main
    :      cli_main_()
    :    File "/home/osboxes/.local/lib/python3.8/site-packages/dt_shell/main.py", line 201, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/osboxes/.local/lib/python3.8/site-packages/dt_shell/cli.py", line 279, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/osboxes/.local/lib/python3.8/site-packages/dt_shell/dt_command_abs.py", line 41, in do_command
    :      cls.commands[word].do_command(cls.commands[word], shell, " ".join(parts[1:]))
    :    File "/home/osboxes/.local/lib/python3.8/site-packages/dt_shell/dt_command_abs.py", line 48, in do_command
    :      cls.command(shell, args)
    :    File "/home/osboxes/.dt-shell/commands-multi/daffy/duckiebot/update/command.py", line 58, in command
    :      login_client_OLD(client, shell.shell_config, registry_to_use, raise_on_error=False)
    :    File "/home/osboxes/.dt-shell/commands-multi/daffy/utils/docker_utils.py", line 200, in login_client_OLD
    :      _login_client_OLD(
    :    File "/home/osboxes/.dt-shell/commands-multi/daffy/utils/docker_utils.py", line 215, in _login_client_OLD
    :      res = client.login(username=username, password=password, registry=registry, reauth=True)
    :    File "/usr/lib/python3/dist-packages/docker/client.py", line 183, in login
    :      return self.api.login(*args, **kwargs)
    :    File "/usr/lib/python3/dist-packages/docker/api/daemon.py", line 152, in login
    :      return self._result(response, json=True)
    :    File "/usr/lib/python3/dist-packages/docker/api/client.py", line 267, in _result
    :      self._raise_for_status(response)
    :    File "/usr/lib/python3/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    :      raise create_api_error_from_http_exception(e)
    :    File "/usr/lib/python3/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    :      raise cls(e, response=response, explanation=explanation)
    :  docker.errors.APIError: 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.53:53: server misbehaving")

dts :  To report a bug, please also include the contents of /home/osboxes/shell-debug-info.txt

**Comment by liampaull** [comment]
this is a connection issue.
