### ISSUE TITLE
dts :  Problems with a command?

### ISSUE THREAD

**Issue by alla82gh** [duckietown/duckietown-shell-commands#383]
Any idea for these error ??
~$ dts --set-version daffy

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)

**Comment by pvirvani** [comment]
1) first remove (factory setting): sudo rm -rf ~/.dt-shell
2) then check version: dts version 

the output will be something liek this:

INFO:dts:Commands version: daffy
INFO:dts:looking at /home/$USER/.dt-shell/commands-multi/daffy
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.1.1 path /home/$USER/.local/lib/python3.8/site-packages
dts version 5.4.5

it should work.

**Comment by afdaniele** [comment]
This used to be a suggestion message (see the question mark): "Problems with a command?"
We removed it to avoid confusion.
