### ISSUE TITLE
Wrong hyperlink for Published Ports for rpi-health in Portainer

### ISSUE THREAD

**Issue by surirohit** [duckietown/duckietown-shell-commands#45]
The entry for Published Ports column for rpi-health in the Portainer interface redirects to http://0.0.0.0:8085/ when it should be redirecting to http://hostname.local:8085/

**Comment by AndreaCensi** [comment]
not something we have control over

0.0.0.0 means it’s listening to all interfaces

**Comment by surirohit** [comment]
I get a "This site can't be reached" error with the first address. Is that normal?

**Comment by AndreaCensi** [comment]
It's not a valid hostname. It's a convention to mean "all interfaces".
