### ISSUE TITLE
Error with "dts start_gui_tools hostname"

### ISSUE THREAD

**Issue by smingko** [duckietown/duckietown-shell-commands#52]
I got an error message when I use the following command:

==================================================================
```
$ dts start_gui_tools james-duckie           
INFO:dts:duckietown-shell 3.0.22

dts :  Problems with a command?
    :  
    :  Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :  Troubleshooting:
    :  
    :  - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :  - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :    (Note: you will have to re-configure.)
/home/james/.dt-shell/commands/.updates-check
Duckietown Shell commands version 1.0.7
INFO:dts:I will ignore DOCKER_HOST in the environment because we want to run things on the laptop.

dts :  Traceback (most recent call last):
    :    File "/home/james/.local/lib/python2.7/site-packages/dt_shell/__init__.py", line 31, in cli_main
    :      cli_main_()
    :    File "/home/james/.local/lib/python2.7/site-packages/dt_shell/__init__.py", line 81, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    :      return func(arg)
    :    File "/home/james/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 408, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/james/.local/lib/python2.7/site-packages/dt_shell/dt_command_abs.py", line 46, in do_command
    :      cls.command(shell, args)
    :    File "/home/james/.dt-shell/commands/start_gui_tools/command.py", line 36, in command
    :      start_gui_tools(parsed_args.hostname)
    :    File "/home/james/.dt-shell/commands/start_gui_tools/command.py", line 42, in start_gui_tools
    :      local_client = docker.from_env()
    :    File "/home/james/.local/lib/python2.7/site-packages/docker/client.py", line 85, in from_env
    :      timeout=timeout, version=version, **kwargs_from_env(**kwargs)
    :    File "/home/james/.local/lib/python2.7/site-packages/docker/client.py", line 40, in __init__
    :      self.api = APIClient(*args, **kwargs)
    :    File "/home/james/.local/lib/python2.7/site-packages/docker/api/client.py", line 118, in __init__
    :      base_url, IS_WINDOWS_PLATFORM, tls=bool(tls)
    :    File "/home/james/.local/lib/python2.7/site-packages/docker/utils/utils.py", line 279, in parse_host
    :      "Bind address needs a port: {0}".format(addr))
    :  DockerException: Bind address needs a port: james-duckie.local
```
===============================================================================

Any suggest to fix this error?

**Comment by AleksandarPetrov** [comment]
Do other commands work for you?
E.g.
`dts keyboard_control hostname`?

**Comment by smingko** [comment]
`dts keyboard_control hostname ` command work fine.
I try to reinstall the dts and run the  `dts start_gui_tools hostname` again.
the screen show like this:

> > $ dts start_gui_tools james-duckie                                                                                                         
> INFO:dts:duckietown-shell 3.0.22
> 
> dts :  Problems with a command?
>     :  
>     :  Report here: https://github.com/duckietown/duckietown-shell-commands/issues
>     :  
>     :  Troubleshooting:
>     :  
>     :  - If some commands update fail, delete ~/.dt-shell/commands
>     :  
>     :  - To reset the shell to "factory settings", delete ~/.dt-shell
>     :  
>     :    (Note: you will have to re-configure.)
> /home/james/.dt-shell/commands/.updates-check
> Duckietown Shell commands version 1.0.7
> access control disabled, clients can connect from any host
> 

than nothing happen.

**Comment by smingko** [comment]
I have try to reinstall the ubuntu(18.04) system and try the `dts start_gui_tools hostname` command again.
Wait a a lone time still can't see the container start.
Here is the error message after I interrupt the command.

> dts :  Traceback (most recent call last):
>     :    File "/home/james/.local/lib/python2.7/site-packages/dt_shell/__init__.py", line 36, in cli_main
>     :      cli_main_()
>     :    File "/home/james/.local/lib/python2.7/site-packages/dt_shell/__init__.py", line 103, in cli_main_
>     :      shell.onecmd(cmdline)
>     :    File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
>     :      return func(arg)
>     :    File "/home/james/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 409, in <lambda>
>     :      do_command_lam = lambda s, w: do_command(klass, s, w)
>     :    File "/home/james/.local/lib/python2.7/site-packages/dt_shell/dt_command_abs.py", line 46, in do_command
>     :      cls.command(shell, args)
>     :    File "/home/james/.dt-shell/commands/start_gui_tools/command.py", line 36, in command
>     :      start_gui_tools(parsed_args.hostname)
>     :    File "/home/james/.dt-shell/commands/start_gui_tools/command.py", line 47, in start_gui_tools
>     :      local_client.images.pull(IMAGE_RPI_GUI_TOOLS)
>     :    File "/home/james/.local/lib/python2.7/site-packages/docker/models/images.py", line 412, in pull
>     :      self.client.api.pull(repository, tag=tag, **kwargs)
>     :    File "/home/james/.local/lib/python2.7/site-packages/docker/api/image.py", line 396, in pull
>     :      stream=stream, timeout=None
>     :    File "/home/james/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 46, in inner
>     :      return f(self, *args, **kwargs)
>     :    File "/home/james/.local/lib/python2.7/site-packages/docker/api/client.py", line 194, in _post
>     :      return self.post(url, **self._set_request_timeout(kwargs))
>     :    File "/home/james/.local/lib/python2.7/site-packages/requests/sessions.py", line 572, in post
>     :      return self.request('POST', url, data=data, json=json, **kwargs)
>     :    File "/home/james/.local/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
>     :      resp = self.send(prep, **send_kwargs)
>     :    File "/home/james/.local/lib/python2.7/site-packages/requests/sessions.py", line 677, in send
>     :      r.content
>     :    File "/home/james/.local/lib/python2.7/site-packages/requests/models.py", line 828, in content
>     :      self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
>     :    File "/home/james/.local/lib/python2.7/site-packages/requests/models.py", line 750, in generate
>     :      for chunk in self.raw.stream(chunk_size, decode_content=True):
>     :    File "/home/james/.local/lib/python2.7/site-packages/urllib3/response.py", line 490, in stream
>     :      for line in self.read_chunked(amt, decode_content=decode_content):
>     :    File "/home/james/.local/lib/python2.7/site-packages/urllib3/response.py", line 666, in read_chunked
>     :      self._update_chunk_length()
>     :    File "/home/james/.local/lib/python2.7/site-packages/urllib3/response.py", line 598, in _update_chunk_length
>     :      line = self._fp.fp.readline()
>     :    File "/usr/lib/python2.7/socket.py", line 451, in readline
>     :      data = self._sock.recv(self._rbufsize)
>     :  KeyboardInterrupt
> 
> dts :  Please report that you are using:
>     :  
>     :  duckietown-shell: 3.0.26
>     :  duckietown-shell-commands: 1.0.13
>     :  python: "2.7.15rc1 (default, Apr 15 2018, 21:51:34) \n[GCC 7.3.0]"
Any suggest ?

**Comment by Petrolkopf** [comment]
> I am also getting this error:
> 
> dts start_gui_tools mrquackers
> INFO:dts:duckietown-shell 3.0.26
> 
> dts : Problems with a command?
> :
> : Report here: https://github.com/duckietown/duckietown-shell-commands/issues
> :
> : Troubleshooting:
> :
> : - If some commands update fail, delete ~/.dt-shell/commands
> :
> : - To reset the shell to "factory settings", delete ~/.dt-shell
> :
> : (Note: you will have to re-configure.)
> Duckietown Shell commands version 1.0.13
> access control disabled, clients can connect from any host

I got the same problem too, did you fix it?

**Comment by gibernas** [comment]
As a temporary solution, unset the `DOCKER_HOST`
