### ISSUE TITLE
"Your git version is too low"

### ISSUE THREAD

**Issue by liampaull** [duckietown/duckietown-shell-commands#56]
When I run `dts docs build` I get this error:

```docs-AIDO$ dts docs build
INFO:dts:duckietown-shell 3.0.24

dts :  Problems with a command?
    :  
    :  Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :  Troubleshooting:
    :  
    :  - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :  - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :    (Note: you will have to re-configure.)
/Users/lpaull/.dt-shell/commands/.updates-check
Duckietown Shell commands version 1.0.7
DEBUG:dts:Checking docker environment
DEBUG:dts:skipping env check because not on Linux
git version: git version 2.19.1

dts :  Your git version is too low, as it does not support --show-superproject-working-tree
    :  
    :  Detected: git version 2.19.1```

even though I think 2.19.1 is the most recent version of git on mac

**Comment by AndreaCensi** [comment]
can you update commands and try again?
It will show more debug information.

**Comment by AndreaCensi** [comment]
@gibernas I put a fix to this. Can you update and try again?

**Comment by gibernas** [comment]
seems to be solved

**Comment by mweiss17** [comment]
I got this error too, but it's unclear how to fix it. Could you add a git commit linked to this issue? I am on Duckietown Shell commands version 1.1.1, and Duckietown Shell 3.0.31 using ubuntu 16.04. Here is my error log:

martin@martin-desktop:~/code/academic/docs-exercises$ dts docs build
INFO:dts:duckietown-shell 3.0.31

dts :  Problems with a command?
    :  
    :  Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :  Troubleshooting:
    :  
    :  - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :  - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :    (Note: you will have to re-configure.)
/home/martin/.local/lib/python2.7/site-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Duckietown Shell commands version 1.1.1
DEBUG:dts:Checking docker environment for user martin
DEBUG:dts:git version: git version 2.7.4
DEBUG:dts:gitdir_super: u'--show-superproject-working-tree'
DEBUG:dts:gitdir: u'/home/martin/code/academic/docs-exercises'

dts :  Your git version is too low, as it does not support --show-superproject-working-tree
    :  
    :  Detected: git version 2.7.4

dts :  Please report that you are using:
    :  
    :  duckietown-shell: 3.0.31
    :  duckietown-shell-commands: 1.1.1
    :  python: "2.7.12 (default, Nov 12 2018, 14:36:49) \n[GCC 5.4.0 20160609]"

**Comment by mweiss17** [comment]
I made sure to run through the installation guide from [here](https://github.com/duckietown/duckietown-shell) for ubuntu 16.04
