### ISSUE TITLE
Wrong username in submission

### ISSUE THREAD

**Issue by hristo-vrigazov** [duckietown/duckietown-shell-commands#60]
I just went through the instructions and managed to submit, but although I authenticated correctly, the name appears wrong in the submission.
See here:
https://challenges.duckietown.org/v3/humans/submissions/404

It says 'Andrea Censi' instead of 'Hristo Vrigazov'

**Comment by AndreaCensi** [comment]
Weird caching bug with the Wordpress database.
Not present in the other devel instance:
https://challenges.duckietown.org/v3-devel/humans/submissions/404

Be sure it's just a visualization bug - the submission is correctly recorded.

**Comment by AndreaCensi** [comment]
fixed some time ago
