### ISSUE TITLE
Unable to find image `duckietown/rip-ros-kinetic-roscore:master18` locally

### ISSUE THREAD

**Issue by liampaull** [duckietown/duckietown-shell-commands#61]
When I burn a fresh SD card and try to run the roscore container it has to download it. 
I thought this was not supposed to be the case with the new SD card flashing script

**Comment by AndreaCensi** [comment]
do you still have tar files in /var/local?

**Comment by AndreaCensi** [comment]
if so then the decompression didn’t finish

**Comment by liampaull** [comment]
I only see 2 stacks at `![robot_name].local:9000/#/stacks` but I feel I should see more if I understand things correctly ?

**Comment by AndreaCensi** [comment]
What is the contents of /var/local?
If you see tar files there then the initial decompression didn't work.

**Comment by breandan** [comment]
`dts init_sd_card` always [pulls](
https://github.com/duckietown/duckietown-shell-commands/blob/b86e9c41291c9b90bdd40525b497176084121cb6/init_sd_card/command.py#L874) the latest version of the image, right? So if the [`master18` tag](
https://hub.docker.com/r/duckietown/rpi-ros-kinetic-roscore/tags/) was updated, Docker will need to fetch it again...
