### ISSUE TITLE
`init_sd_card` complains about `tok set` but too late

### ISSUE THREAD

**Issue by afdaniele** [duckietown/duckietown-shell-commands#63]
I tried to run `init_sd_card` after a fresh install of the shell and after downloading, flashing and other things, the command crashed and asked to run `dts tok set` and try again.

We should check this before starting the flashing process.

I'm using:
```
    :  duckietown-shell: 3.0.30
    :  duckietown-shell-commands: 1.0.15
    :  python: "2.7.12 (default, Dec  4 2017, 14:50:18) \n[GCC 5.4.0 20160609]"
```

**Comment by jasonhu5** [comment]
Seems fixed already: https://github.com/duckietown/duckietown-shell-commands/blob/37bc557bbce5488ff85b1c98db5a5fa91b248b46/init_sd_card/command.py#L184
