### ISSUE TITLE
give an option for dynamic hostname 

### ISSUE THREAD

**Issue by AndreaCensi** [duckietown/duckietown-shell-commands#7]
If you have 40 traffic lights + 40 robots, it is useful to just replicate the SD card with a hw device.

However currently this cannot be done because the hostname would be the same across the board.

Changing the hostname is tedious because you need to do it for each container.

One way to handle the situation is to have the hostname being generated on first boot.

For example, by using the mac address of eth0:

mac: b8:27:eb:bc:e8:21
hostname: DTb827ebbce821

Then we take care of the pretty names at a higher level.

Note: also this would allow complete zero-interaction setup with an app:

"Instructions: insert the SD card, connect the duckiebot to the router with the ethernet cable, and run this app on your phone"

The app would look for all devices named DT****** and then from there we can configure everything else.

**Comment by AndreaCensi** [comment]
@breandan @afdaniele see above. What do you think?

**Comment by afdaniele** [comment]
Love it!

**Comment by breandan** [comment]
This should be possible (we were configuring the Duckiebot SSID dynamically, [based on the MAC address](https://github.com/duckietown/duckietown-shell-commands/blob/master/init_sd_card.scripts/init_sd_card.sh#L234)), but I'm not sure how to configure the hostname dynamically, which is set at the [beginning of the cloud-init config](https://github.com/duckietown/duckietown-shell-commands/blob/b9d547883dd379e2c5c85d6f3806cdfaeaffa5c3/init_sd_card.scripts/init_sd_card.sh#L135) (it should be possible to alter this on first boot in a similar to the SSID name).

**Comment by hosnerm** [comment]
That sounds really nice, have there been any proceedings on that yet?

**Comment by jasonhu5** [comment]
With the DuckieDrone21 (DD21) setup procedure, the request to change hostnames after flashing SD card could be achieved. Namely, the same image is flashed to SD cards, and the `hostname`s are changed by changing a txt file before first boot. All containers/topics will use that name.

Although it is not dynamic hostnaming, the big interests of duplicating cards with hw devices and changing hostnames easily are possible. So closing this for now unless the need for online dynamic hostnaming appears very important
