### ISSUE TITLE
init_sd_card cannot work (Cannot communicate with Docker)

### ISSUE THREAD

**Issue by catmasteryip** [duckietown/duckietown-shell-commands#71]
![image](https://user-images.githubusercontent.com/29121012/48340842-94310400-e6a6-11e8-9ccf-f0f32d6695b5.png)

**Comment by AleksandarPetrov** [comment]
It is likely that you're user is not in the `docker` group. You can check that by running `groups`. If you follow the instructions on the Duckumentation, it's described there how to add your user. Note that you have to log out and in again for the changes to take effect.

**Comment by liampaull** [comment]
doesn't fix:
```lpaull:~$ sudo adduser `whoami` docker
The user `lpaull' is already a member of `docker'.
lpaull:~$ dts init_sd_card --linux-username tlo --hostname trafficlight1
INFO:dts:duckietown-shell 3.0.30

dts :  Problems with a command?
    :  
    :  Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :  Troubleshooting:
    :  
    :  - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :  - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :    (Note: you will have to re-configure.)
Duckietown Shell commands version 1.1.1


## Tips and tricks

### Multiple networks

    dts init_sd_card --wifi  network1:password1,network2:password2 --country US



### Steps

Without arguments the script performs the steps:

    flash
    expand
    mount
    setup
    unmount

You can use --steps to run only some of those:

    dts init_sd_card --steps expand,mount



    
DEBUG:dts:Checking docker environment for user lpaull

dts :  I cannot communicate with Docker:
    :  'function' object has no attribute 'list'
    :  
    :  Make sure the docker service is running.

dts :  Please report that you are using:
    :  
    :  duckietown-shell: 3.0.30
    :  duckietown-shell-commands: 1.1.1
    :  python: "2.7.12 (default, Nov 12 2018, 14:36:49) \n[GCC 5.4.0 20160609]"
```

**Comment by liampaull** [comment]
and docker service is running 
@AndreaCensi @breandan any ideas?

**Comment by liampaull** [comment]
suggestion of @AleksandarPetrov doesn't fix for me - @AndreaCensi @breandan any suggestions,

**Comment by breandan** [comment]
Hmm, can you check the permissions on `/var/run/docker.sock`, `/usr/bin/docker` and if necessary take ownership of these files? Afterwards, try restarting the Docker daemon (either by `sudo service docker restart` or rebooting). c.f. https://stackoverflow.com/questions/29703274/python-docker-py-connection-refused

**Comment by liampaull** [comment]
@breandan restarting the service resets the permissions

**Comment by breandan** [comment]
Resets the permissions as in, the permissions are fixed, or the permissions are still broken?

**Comment by liampaull** [comment]
I'm not convinced this was the issue - but I'm not sure what was - some combination of reboots and updates of the shell seems to have fixed this so I will close

**Comment by breandan** [comment]
Unable to reproduce. If anyone else encounters this issue maybe just nuke your Docker and reinstall from scratch.

https://gist.github.com/breandan/27620ceaa53b31d720a99ffdcbdf55f9

**Comment by catmasteryip** [comment]
@AleksandarPetrov  suggestion worked and it was resolved days before today. Thanks

**Comment by liampaull** [comment]
oh man this problem is back for me...

**Comment by liampaull** [comment]
This was finally fixed with uninstalling docker-py (`pip uninstall docker-py`) then installing the `docker` python package
