### ISSUE TITLE
dts keyboard_control doesnt work

### ISSUE THREAD

**Issue by Guniii** [duckietown/duckietown-shell-commands#73]
When using "dts keyboard_control hostname" an unknown syntax error shows up.

Just a few days ago it used to work without any problems and now suddenly it gives me this error.

**Comment by AndreaCensi** [comment]
@Guniii please include complete output

**Comment by Guniii** [comment]
Problem solved: it was moved to a new folder duckietown

The new command should be: "dts duckietown keyboard_control hostname"
