### ISSUE TITLE
init_sd_card failed: pull access denied for duckietown/rpi-duckiebot-camera-node

### ISSUE THREAD

**Issue by catmasteryip** [duckietown/duckietown-shell-commands#75]
![image](https://user-images.githubusercontent.com/29121012/48616617-171bcc80-e9cf-11e8-98c4-747c767cbbec.png)

**Comment by catmasteryip** [comment]
I checked the repo is there and it is available for master branch 18

**Comment by breandan** [comment]
Hmm, `duckietown/rpi-duckiebot-ros-picam` was indeed archived as per duckietown/rpi-duckiebot-camera-node#1. But I’m not sure how this ever worked to begin with, since according to that issue it wasn’t using `masterYY` nomenclature.

**Comment by hosnerm** [comment]
Did anyone find out how to resolve this error? i have the same problem, and it doesn't work for me either (even after login)

**Comment by breandan** [comment]
Would you attach the error you are receiving? The original error should have been fixed.

**Comment by hosnerm** [comment]
i updated the comment above, just the same error as appears in the topmost post
