### ISSUE TITLE
init_sd_card: cannot ping: unknown host duckiebot.local

### ISSUE THREAD

**Issue by catmasteryip** [duckietown/duckietown-shell-commands#76]
i have successfully burnt the sd card. However I could not ping the bot after 5.1 in operation manual. 
`$ ping duckiebot.local`
`ping: unknown host duckiebot.local`
my sd initialization command:
`dts init_sd_card`
is it because i did not set the country option properly (I am not in US)?
I am using native ubuntu16.

**Comment by breandan** [comment]
The country code might be necessary, but in my experience (Canada) it is not important. It can take a while to unzip all the packages. Did you give it about 10-15 minutes to complete the first boot? Are you in vicinity of a configured router (`Duckietown`/`quackquack` by default)? Can you see if the Duckiebot is connected to the router via the router’s admin interface? If so, can you ping it by the IP address or can you ping other devices on the network by their mDNS name? Have you tried connecting an Ethernet cable and pinged the Duckiebot?

Note to self: we should add these steps to the network troubleshooting.

**Comment by AK51** [comment]
I have the same problem. Also, I did explicitly type in all options including country, hostnames... same problem, no wifi connection.
I also tried to plug in the ethernet cable and HDMI/keyboard. I can ping the board, 
but the login/password of duckie/quackquack is wrong even through in local keyboard/hdmi.

**Comment by breandan** [comment]
Thank you for reporting. Did you change the username from `duckie` or the default password from `quackquack`? What username was displayed initially when you attempted to log in via HDMI/keyboard? Were you in the vicinity of a Duckietown configured router, and did you ever see the Duckiebot connect to the router via the router's admin interface? If you can ping the board via `ping <HOSTNAME>.local`, then you should be able to log in via `ssh <USERNAME>@<HOSTNAME>.local`.

If all else fails, you can check to see what the username and password are by removing the SD card from the Duckiebot, inserting it into the computer, and opening the file `/media/<USERNAME>/HypriotOS/user-data` (on Ubuntu) and you should be able to see the hostname and username.
