### ISSUE TITLE
Unable to reflash SD card

### ISSUE THREAD

**Issue by Petrolkopf** [duckietown/duckietown-shell-commands#78]
Flashing Hypriot image /tmp/duckietown/hypriotos-rpi-v1.9.0.img.zip to disk /dev/sdc
? This will erase the selected drive. Are you sure? Yes
Unexpected token x in JSON at position 1775

dts :  Traceback (most recent call last):
    :    File "/home/dieselkopf/.local/lib/python2.7/site-packages/dt_shell/__init__.py", line 38, in cli_main
    :      cli_main_()
    :    File "/home/dieselkopf/.local/lib/python2.7/site-packages/dt_shell/__init__.py", line 106, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    :      return func(arg)
    :    File "/home/dieselkopf/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 409, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/dieselkopf/.local/lib/python2.7/site-packages/dt_shell/dt_command_abs.py", line 47, in do_command
    :      cls.command(shell, args)
    :    File "/home/dieselkopf/.dt-shell/commands/init_sd_card/command.py", line 190, in command
    :      step2function[step_name](shell, parsed)
    :    File "/home/dieselkopf/.dt-shell/commands/init_sd_card/command.py", line 269, in step_flash
    :      raise Exception(msg)
    :  Exception: An error occurred while initializing the SD card, please check and try again (1).

dts :  Please report that you are using:
    :  
    :  duckietown-shell: 3.0.31
    :  duckietown-shell-commands: 1.1.1
    :  python: "2.7.12 (default, Nov 12 2018, 14:36:49) \n[GCC 5.4.0 20160609]"

**Comment by Petrolkopf** [comment]
> Flashing Hypriot image /tmp/duckietown/hypriotos-rpi-v1.9.0.img.zip to disk /dev/sdc
> ? This will erase the selected drive. Are you sure? Yes
> Unexpected token x in JSON at position 1775
> 
> dts : Traceback (most recent call last):
> : File "/home/dieselkopf/.local/lib/python2.7/site-packages/dt_shell/**init**.py", line 38, in cli_main
> : cli_main_()
> : File "/home/dieselkopf/.local/lib/python2.7/site-packages/dt_shell/**init**.py", line 106, in cli_main_
> : shell.onecmd(cmdline)
> : File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
> : return func(arg)
> : File "/home/dieselkopf/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 409, in 
> : do_command_lam = lambda s, w: do_command(klass, s, w)
> : File "/home/dieselkopf/.local/lib/python2.7/site-packages/dt_shell/dt_command_abs.py", line 47, in do_command
> : cls.command(shell, args)
> : File "/home/dieselkopf/.dt-shell/commands/init_sd_card/command.py", line 190, in command
> : step2function[step_name](shell, parsed)
> : File "/home/dieselkopf/.dt-shell/commands/init_sd_card/command.py", line 269, in step_flash
> : raise Exception(msg)
> : Exception: An error occurred while initializing the SD card, please check and try again (1).
> 
> dts : Please report that you are using:
> :
> : duckietown-shell: 3.0.31
> : duckietown-shell-commands: 1.1.1
> : python: "2.7.12 (default, Nov 12 2018, 14:36:49) \n[GCC 5.4.0 20160609]"

It seems it is the problem of the Etcher when flash image to the SD card, and the script complains: 
```Unexpected token x in JSON at position 1775```

**Comment by breandan** [comment]
Could it be a caching issue, did the original download complete? Try removing the tmp  file and trying again, we were able to flash a number of cards recently and did not encounter this issue.

**Comment by Petrolkopf** [comment]
> Could it be a caching issue, did the original download complete? Try removing the tmp file and trying again, we were able to flash a number of cards recently and did not encounter this issue.

I already tried it (delete the "/tmp/duckietown" floder) but it doesn't help. I also tried to farmat the SD card manually and then flash the card.

I looked into the code of ```init_sd_card2.sh```, and it turns out

 ```sudo -p "[sudo] Enter password for '%p' which is required to run Etcher: " ${ETCHER_DIR}/etcher -d ${INIT_SD_CARD_DEV} -u false ${HYPRIOT_LOCAL}```

raised error ```Unexpected token x in JSON at position 1775```.

Now I temporally make it work by changing the script of ```init_sd_card2.sh``` to the **resin** version instead of **balena**.

**Comment by hzy5000** [comment]
I had the same problem. Just change the etcher version from 1.4.6 to 1.4.4 in the ~/.dt-shell/commands/init_sd_card/init_sd_card2.sh, then the problem will be solved.
