### ISSUE TITLE
the home created on the duckiebot is owned by root

### ISSUE THREAD

**Issue by AndreaCensi** [duckietown/duckietown-shell-commands#8]
For the default user "duckie", the directory "~duckie" is owned by root.

FYI @breandan

**Comment by AndreaCensi** [comment]
Currently there is a workaround in the documents but this is a bug.

**Comment by liampaull** [comment]
low priority for now - we have way bigger fish to fry

**Comment by AndreaCensi** [comment]
fixed in init_sd_card2
