### ISSUE TITLE
Could not find docker-compose

### ISSUE THREAD

**Issue by AK51** [duckietown/duckietown-shell-commands#91]
I can login the duckie car through wifi, however, when I build the SD card, there are some error, does it matter? Thx
![error](https://user-images.githubusercontent.com/8468724/51526971-80f0a080-1e6e-11e9-81f5-94c0a4030e91.jpg)

**Comment by AK51** [comment]
When I tried to open the IE of http://duckiebot.local:9000/#/containers, it refused.
Is it because of the Error above? Thx

**Comment by liampaull** [comment]
@AK51 is this still an issue? if not please close
