### ISSUE TITLE
dts duckiebot calibrate_wheels  does not mount /data from host

### ISSUE THREAD

**Issue by davesnowdon** [duckietown/duckietown-shell-commands#92]
I successfully completed camera calibration and verified that the files were present in /data/config/calibrations/camera_intrinsic & /data/config/calibrations/camera_extrinsic

I got a shell on the robot by running `dts duckiebot calibrate_wheels duckiebot2` but when I ran make hw-test-kinematics I saw a warning message that `/data/config/calibrations/camera_intrinsic/duckiebot2.yaml` could not be found and the default would be used. After the command completed (and the test had failed) I looked in /data and the camera calibration files were not visible within the container.

Looking in $HOME/.dt-shell/commands/duckiebot/calibrate_wheels/calibrate_duckiebot.sh showed that the command used to launch the container on the duckiebot was:

   ` docker -H "$DUCKIEBOT_NAME.local" run -it --net host --privileged  $IMAGE_BASE /bin/bash`

surely it should use the -v option, like this:

   ` docker -H "$DUCKIEBOT_NAME.local" run -it --net host --privileged  -v /data:/data $IMAGE_BASE /bin/bash`

**Comment by breandan** [comment]
> surely it should use the -v option, like this:
>
>   ` docker -H "$DUCKIEBOT_NAME.local" run -it --net host --privileged  -v /data:/data $IMAGE_BASE /bin/bash`

Good catch! It would seem so, thank you for investigating.
