### ISSUE TITLE
dts challenges evaluate error

### ISSUE THREAD

**Issue by LeulShiferaw** [duckietown/duckietown-shell-commands#93]
dts challenges submit works but evaluate gives this error: 

INFO:dts:Cannot get container local-evaluator: 404 Client Error: Not Found ("No such container: local-evaluator")
DEBUG:dts:monitoring graceful exit

**Comment by liampaull** [comment]
submit will give you a 404 if the challenge is closed. I was able to successfully run `dts challenges evaluate` though so unable to reproduce. Possible that you were not connected to internet (needed for evaluate)
