### ISSUE TITLE
error " I cannot communicate with Docker" using dts init_sd_card 

### ISSUE THREAD

**Issue by alifahriander** [duckietown/duckietown-shell-commands#96]
Hello everyone,

I wanted to flash an SD card but I get the following error : 

dts :  I cannot communicate with Docker:
    :  load_config() got an unexpected keyword argument 'config_dict'
    :  
    :  Make sure the docker service is running.

dts :  Please report that you are using:
    :  
    :  duckietown-shell: 3.0.31
    :  duckietown-shell-commands: 1.1.1
    :  python: "2.7.12 (default, Nov 12 2018, 14:36:49) \n[GCC 5.4.0 20160609]"

I tried to uninstall Docker and install it again following the instructions from https://docs.docker.com/install/linux/docker-ce/ubuntu/  but I still got the same error.

After the reinstallation, "$docker version" outputs as follows :
 
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:40:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false

What should I do?

**Comment by breandan** [comment]
Thanks for reporting. We encountered a [similar error](https://www.duckietown.org/forums/topic/error-make-sure-docker-is-running) last year, also possibly related: #71. Would you please run the command `python -c "import docker; print(docker.from_env().version())"` and paste the output below?
